### ISSUE TITLE
Autocomplete Function Parameters

### ISSUE THREAD

**Issue by rica-benhossi** [sadovnychyi/autocomplete-python#100]
I don't know if it is a really issue, but even I set Autocomplete Function Parameters to ALL, it doesn't complete the command with all arguments when I type enter or tab in the hint that I choose

**Comment by patrys** [comment]
Have you tried opening the parenthesis right after a function name? We don't complete parameters by default as sometimes you want to operate on functions and classes without actually calling them.

**Comment by rica-benhossi** [comment]
I see... I tried in PRINT and INPUT functions only but it doesn't complete with (""). Is the correct in this case or it should have completed with ("")?

**Comment by patrys** [comment]
`print` is a statement in Python 2 so we cannot easily complete any parameters.

`input` is a function and has one optional parameter so if you choose to include all parameters, it should give you:

```python
input(prompt=None)
```

**Comment by rica-benhossi** [comment]
Right. Thanks for your quick reply @patrys . I tried INPUT while change a lot of configurations, but it still doesn't show anything before tap ENTER or TAB keys. I'm using Python 3.5 (x64 installed directly in C:\Python) and Jedi is installed too.
Sorry about my rookies mistakes. I'm kind of noob in Python. I have been learning about it since last month and I'm really enjoying this. I think that this feature could help me to understand the language more quickly... Thanks for helping me.

**Comment by sadovnychyi** [comment]
Function arguments are getting completed if you have config option set to `all` or `required`. But they are getting completed only after you type an open bracket character `(`. 

![sample](https://cloud.githubusercontent.com/assets/193864/10810226/a842f6a2-7e39-11e5-8e69-bd6370e5f114.gif)

Is some cases though its does not works properly. For example, if I open new tab & set syntax to Python – I'm not getting any argument completions there. This is a bug and I'll investigate it.

**Comment by rica-benhossi** [comment]
I think that the problem is in Jedi. Actually is not a problem, but maybe a version mismatch. I was reading the Jedi documentation and I saw this: "You can run Jedi on cPython 2.6, 2.7, 3.2, 3.3 or 3.4, but it should also understand/parse code older than those versions". I was running Python 3.5, so I uninstall both applications, atom and python 3.5 and installed them again, but this time I had installed Python3.4. Suddenly it works... finally. I'll run more tests with Python 3.5 and Jedi beta to see if it works, but it's clear that the problem is not in your atom package. Thank you both very much for helping me through this and sorry about my rookies mistakes...

**Comment by sadovnychyi** [comment]
I can confirm that argument completions broken on current atom beta for me, fixing it already.
Glad that you resolved your problem anyway.

**Comment by sadovnychyi** [comment]
Now arguments completion will work if you change your grammar to become python from something else. Also we will not listen to keyup events if you change your grammar to non-python.
