### ISSUE TITLE
Very slow completion

### ISSUE THREAD

**Issue by albireox** [sadovnychyi/autocomplete-python#102]
For a few days I have been noticing that autocomplete-python takes ages to show the pop up menu with suggestions, and that it uses the CPU very aggressively. Looking at the debug logs, it seems that autocomplete sends the serialised request to Jedi quickly, and also receives the response from Jedi quite quickly. But then there is a very long lag (sometimes up to a minute) until the menu with the suggestions pops up. In the meantime, there is a Python process using 100% of the CPU (not sure what it is doing).

The problem seem to appear after Atom has been opened for a few minutes. When I just restart Atom the autocompletion works well for a few minutes, and then the lags appear.

Other than that autocomplete-python works well, and the suggestions are correct, but this lag makes it completely unusable. If I disable autocomplete-python the rest of the Atom completion works well. I'm using Atom 1.0.19 (tried it also with the beta version and the problem remains), Mac OSX 10.11, and Python 2.7.10.

**Comment by sadovnychyi** [comment]
Are you seeing any errors with "Output provider errors" set to true?

![image](https://cloud.githubusercontent.com/assets/193864/10837786/70a74760-7ef8-11e5-8c13-ec99944b322d.png)

**Comment by albireox** [comment]
No. I set it to true several days ago to see if that would give me some clue, but I haven't got any error so far.

**Comment by sadovnychyi** [comment]
Strange. I will try to add more debug options to try to catch this. No ideas for now.

**Comment by albireox** [comment]
Ok, thanks. Let me know if I can help in any way.

**Comment by patrys** [comment]
I suspect that on slower machines with many imports the fuzzy search change could be part of why it's slower. One improvement would be to add fuzzy filtering on the Python side so we don't send huge amounts of data. Another would be to disable the jedi column hack that enables fuzzy autocomplete to see if it makes things significantly faster and if so, make it a setting.

**Comment by sadovnychyi** [comment]
@albireox can you try [v0.6.3](https://github.com/sadovnychyi/autocomplete-python/releases/tag/v0.6.3) where we don't yet have fuzzy completions implemented? Just download, unpack and put it into `~/.atom/packages`

**Comment by albireox** [comment]
When I unpack 0.6.3 and restart Atom, I get this error

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.2
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v0.6.3


### Stack Trace

Failed to load the autocomplete-python package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/Users/albireo/.atom/packages/autocomplete-python/lib/definitions-view.coffee:1:24)
    at Object.<anonymous> (/Users/albireo/.atom/packages/autocomplete-python/lib/definitions-view.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "nucleus-dark-ui",
      "one-dark-syntax"
    ],
    "projectHome": "/Users/albireo/Documents/Repo"
  },
  "autocomplete-python": {
    "extraPaths": "/Users/albireo/Documents/Repo/manga/Totoro;/Users/albireo/Documents/Repo/sdss/sdss_python_module/python;/Users/albireo/Documents/Repo/manga/mangadesign/python",
    "showDescriptions": false,
    "pythonPath": "/usr/local/bin",
    "useSnippets": "required",
    "outputDebug": true,
    "outputProviderErrors": true
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
autocomplete-paths, v1.0.2
autocomplete-python, v0.9.4
highlight-selected, v0.10.1
linter, v1.10.0
linter-flake8, v1.9.1
nucleus-dark-ui, v0.6.6
project-manager, v2.6.5
synced-sidebar, v0.4.2

# Dev
No dev packages
```

**Comment by sadovnychyi** [comment]
You need to run `npm install` from package directory.

**Comment by albireox** [comment]
I guess you meant `apm install`, but yes, that worked.

With v0.6.3 autocomplete-python seems to work fast again. I've been testing it for about one hour and I don't see the lag reappear. The CPU use is also more reasonable.

**Comment by kkHAIKE** [comment]
mbp 2012mid,3 import,back to v0.6.3 after this issue

**Comment by sadovnychyi** [comment]
Could you guys @albireox @kkHAIKE try [this](https://github.com/sadovnychyi/autocomplete-python/releases/tag/v0.9.5pre) one?
I made fuzzy matcher optional and disabled by default. Can you try with that setting turned off and on please?

**Comment by kkHAIKE** [comment]
turn off for speedup

**Comment by sadovnychyi** [comment]
It should be slow with Fuzzy Matcher turned on, and fast with turned off. Can you confirm this?

**Comment by kkHAIKE** [comment]
no , off or on, seem like no difference;

**Comment by patrys** [comment]
Could it be param name completion then?

**Comment by sadovnychyi** [comment]
Just to be sure, @kkHAIKE can you try it with argument completions disabled? Any speed difference? 
![image](https://cloud.githubusercontent.com/assets/193864/10863904/635d743e-8016-11e5-859b-ba36cca0fb01.png)

**Comment by kkHAIKE** [comment]
when set fuzzy on,then reload atom,
first complete is fast,next slower, next slower then befroe

**Comment by kkHAIKE** [comment]
my test method:

```python
import urllib2
import json
import subprocess
```

then type url <space> <pot> url <space> <enter>
```python
urllib2.urlopen
urllib2.urlopen
urllib2.urlopen
.....more
```

**Comment by albireox** [comment]
I'm not completely sure myself. 0.9.5pre without fuzzy completion is clearly faster than 0.9.5pre with fuzzy completion. It seems to me that, even without fuzzy completion, this version is a bit slower than 0.6.3, but I may be wrong. In any case, with fuzzy disabled the plugin is usable.

On the other hand, I wonder why this happens to only a few of us. My computer is a MBA mid-2012 i7 2.0 8 GB RAM, so while it not a cutting-edge machine, it cannot be regarded as slow. I've used Jedi with Sublime and it has always working blitzing fast.

**Comment by sadovnychyi** [comment]
I agree that this is strange behaviour, you machine seems powerful enough. But since it looks like its problem in Jedi (you got 100% CPU on python process) – not sure that I can fix it.

You can update to 0.10.0 with option to disable fuzzy matcher. 
I'm closing this issue but I'm open to PRs with ideas about how to properly fix this.

**Comment by can-z** [comment]
I am also experiencing the same problem constantly, and this issue is by far the biggest thing that makes me going between sublime (sublime jedi is fast for me as well) and atom at the moment and I really think that this issue should stay open to increase visibility. 

Also the slowness only happens when it does the first search on any object so it appears that the result is cached properly but the initial search takes much longer.

**Comment by albireox** [comment]
Yes, I’m seeing this again (in fact I wonder if the problem ever disappeared). In my case it works well for a few minutes to about 30 minutes and then it becomes completely unusable. I’ve been trying to identify if there is a specific import that breaks things, or a combination of Atom plugins, but so far it seems to happen whatever I do.


On November 6, 2015 at 09:28:45, Can Zhang (notifications@github.com) wrote:

I am also experiencing the same problem constantly, and this issue is by far the biggest thing that makes me going between sublime (sublime jedi is fast for me as well) and atom at the moment and I really think that this issue should stay open to increase visibility.

Also the slowness only happens when it does the first search on any object so it appears that the result is cached properly but the initial search takes much longer.

**Comment by can-z** [comment]
This morning I found that "fuzzy search" was turned on in the settings and the slowness has seemingly gone away after I turned it off (haven't happened for 6-7 hours now). I am using the latest (mid 2015) Macbook (2.7G i5, 8G ram) with a VM taking up 4G of the ram.

**Comment by sadovnychyi** [comment]
@albireox is it still slow for you will fuzzy search turned off? It is enabled by default.

**Comment by albireox** [comment]
No, it's turned off. Disabling the fuzzy search definitively has an effect, if only by delaying the point when the plugin starts taking very log to complete, but it does not completely solve the problem for me. Is there a way to get a more detailed log of what autocomplete-python or Jedi are doing, or to profile them?

**Comment by sadovnychyi** [comment]
Possible related to #112 due to high memory usage after a while.

**Comment by albireox** [comment]
Not sure if this helps, but this problem may, in part, be related to the version of Python installed. A few days ago, for an unrelated reason, I reinstalled python building it from source with homebrew. The version I had before was also from homebrew but it was a precompiled package. With the new version. the slowness seems to have mostly gone away, as long as fuzzy is disabled.

In any case, there must be a deeper reason for this bug, as using fuzzy breaks the completion almost immediately, but hopefully this may give a clue to solve the problem.

**Comment by sadovnychyi** [comment]
Added some logic to terminate process if there are more than 10 requests in queue. Maybe it will help. No changes for fuzzy completions anyway. They are going to be slower.

**Comment by sadovnychyi** [comment]
I believe we can make fuzzy matcher a lot faster by making first character to always match.

Right now, you can type just end of completion and you will still get it:
![image](https://cloud.githubusercontent.com/assets/193864/11584313/ec054ef0-9a9d-11e5-9330-a995fb63fcf9.png)
It makes sense, this is how command palette works in Atom, but it requires a lot of work from Jedi.

Instead, we can always include first character for Jedi limiting the search scope.

So, to match ValueError you must type "v" first.
![image](https://cloud.githubusercontent.com/assets/193864/11584334/2e13560c-9a9e-11e5-84b0-ed9221422e3a.png)

**Comment by patrys** [comment]
That's a neat idea. It will also severely limit the amount of serialised items.

**Comment by sadovnychyi** [comment]
Pushed it. Could you guys check it out?

We also could cache requests with same character, since there are no difference for Jedi. This will lead to almost immediate completions after typing anything after first character. But it will require some work to generate request ID without looking on prefixes.

**Comment by albireox** [comment]
That fix seems to have worked nicely. I've been using the package for a couple hours, with the fuzzy completion activated, and so far it works lightning fast. I'll keep an eye on it during the next few days, but this seems to have solved the problem, at least for me.

**Comment by sadovnychyi** [comment]
With #130 I think we could use fuzzy matcher all the time. It should be even faster than without it because of caching.

**Comment by sadovnychyi** [comment]
Would be great if somebody could test that PR! Should be much faster.

**Comment by sadovnychyi** [comment]
@albireox can you give some feedback please?

As for me we should get fuzzy search back on by default, since it gives some performance boost. Cannot find any issues while using it.

**Comment by albireox** [comment]
I think this issue can be closed. I have been using the package for several days with fuzzy completion activated and it works really fast, and the performance doesn't seem to slow down with time. Yet, I have had a couple occurrences of the process starting to use a lot of CPU, and I have had to restart Atom. But I cannot reproduce those cases, and they seem to be extremely sporadic.

**Comment by sadovnychyi** [comment]
Ok, thanks! FYI python process getting killed every 10 minutes, as well as when there are too many requests sent without response.
You can safely kill python process only, without restarting whole editor. It will be spawned again on next usage.
