### ISSUE TITLE
KeyError: 'prefix' on OS X

### ISSUE THREAD

**Issue by walles** [sadovnychyi/autocomplete-python#110]
Hi!

I'm not getting any completions whatsoever from autocomplete-python.

If I enable "Output Provider Errors" in the config, I get a lot of these however:
```
autocomplete-python traceback output: Traceback (most recent call last):
  File "/Users/walles/.atom/packages/autocomplete-python/lib/completion.py", line 257, in watch
    self._process_request(self._input.readline())
  File "/Users/walles/.atom/packages/autocomplete-python/lib/completion.py", line 248, in _process_request
    request['prefix']))
KeyError: 'prefix'
```

This is on OS X 10.11.1, Atom 1.1.0 and autocomplete-python 0.10.0.

**Comment by sadovnychyi** [comment]
Hm, can you confirm that you have `prefix: prefix` on line 217 in file `/Users/walles/.atom/packages/autocomplete-python/lib/provider.coffee`?
The errors suggests that it is not there, and your package may be corrupted. If it's not there – try to reinstall package, if it's there – let me know and I'll look for fix.

**Comment by walles** [comment]
`prefix: prefix` is there on line 217, and the code looks like your screenshot AFAICT.  The md5sum of my `provider.coffee` is `62e8221f6cb16427b821cadb72e6b26f`.

Uninstalling and then re-installing autocomplete-python doesn't help.

  Regards /Johan

**Comment by sadovnychyi** [comment]
Please try 0.10.1.

**Comment by walles** [comment]
0.10.1 fixed it and it now seems to work again. Thanks @sadovnychyi!
