### ISSUE TITLE
Autocompleting function parameters not working?

### ISSUE THREAD

**Issue by walles** [sadovnychyi/autocomplete-python#111]
Maybe I'm just using them wrong, but I've tried this...

1. Set Autocomplete Function Parameters in the Settings to "all".
2. Type (in a buffer with `subprocess` imported): "`subprocess.Po`".
3. Accept the `subprocess.Popen` suggestion by pressing return.

No parameters are suggested.

According to the docs displayed by Autocomplete Python, `subprocess.Popen` has two mandatory parameters, shouldn't they have been suggested?

Typing an opening parenthesis after `subprocess.Popen` doesn't change anything.

Typing an opening bracket (`[`) as suggested in the Settings (this is strange) doesn't change anything.

Is the feature broken or am I just using it wrong?

I'm on Atom 1.1.0 on OS X 10.11.1 and autocomplete-python 0.10.1.

  Regards /Johan

**Comment by sadovnychyi** [comment]
Sorry for confusing about parenthesis/bracket – I'll fix this in docs.
Of course its supposed to open on `(`. Can you enable debug logs in package settings, try to make argument completions, and send me logs from your dev tools?

![image](https://cloud.githubusercontent.com/assets/193864/10935205/6bd3d0c0-831f-11e5-8bd0-0b92a8bfd8db.png)

Note that these logs will contain source files you have edited.

Is there are something like `Trying to complete arguments after bracket...` in the logs?

**Comment by walles** [comment]
Log here: https://gist.github.com/walles/e7aa580de154c1c3ba90

I did it in an empty file:
```python
import submodule

submodule.Popen(
```

No mention of any arguments in the log.

Does this example work for you?

**Comment by sadovnychyi** [comment]
Can you restart your editor and generate another one?
On startup, or when new editor is created, there's should be a log entry with something like `Subscribed on event 333.keyup` which means that atom is ready to trigger argument completion when you will press `(`.

**Comment by walles** [comment]
When I switch the mode of my scratch buffer to "Python" I get "`Subscribed to event 449.keyup`" in the log, no `333`.

**Comment by sadovnychyi** [comment]
That's OK, it has to be different.
If you have this log entry, but no `Trying to complete arguments after bracket...` – it seems like Atom didn't catch your key press.

It's listens on shift key + key with code 57, which is `9` or `(`. 

[Here](http://www.expandinghead.net/keycode.html) I can see that they have some codes with key presses with shift already. Maybe that's an issue. Not sure. 

Could you expand logging to include all keyup events? Just to understand what happening.
Just hardcode new line in `autocomplete-python/libs/provider.coffee` on line 100 to become like this:
![image](https://cloud.githubusercontent.com/assets/193864/10935770/4f37d2fa-8323-11e5-8242-b8e03290d508.png)
Then restart your editor and look for this log message. You can expand the object from console to see shift key event and key code.

![image](https://cloud.githubusercontent.com/assets/193864/10935832/ade3e9c4-8323-11e5-8b9b-5b82bef41009.png)

**Comment by sadovnychyi** [comment]
Note that it will log messages for *each* keyup event, so don't press anything after you type a bracket to see it.

**Comment by walles** [comment]
This is for "`()`":
```
activate linter-eslint
activating linter-flow
activate linter-htmlhint
Window load time: 1285ms
Subscribed on event 35.keyup
KeyboardEvent {}altKey: falsebubbles: truecancelBubble: falsecancelable: truecharCode: 0ctrlKey: falsecurrentTarget: nulldefaultPrevented: falsedetail: 0eventPhase: 0keyCode: 56keyIdentifier: "U+0028"keyLocation: 0layerX: 0layerY: 0location: 0metaKey: falsepageX: 0pageY: 0path: Array[16]repeat: falsereturnValue: trueshiftKey: truesrcElement: atom-text-editor.editortarget: atom-text-editor.editortimeStamp: 1446634074405type: "keyup"view: Windowwhich: 56__proto__: KeyboardEvent
KeyboardEvent {}altKey: falsebubbles: truecancelBubble: falsecancelable: truecharCode: 0ctrlKey: falsecurrentTarget: nulldefaultPrevented: falsedetail: 0eventPhase: 0keyCode: 16keyIdentifier: "Shift"keyLocation: 1layerX: 0layerY: 0location: 1metaKey: falsepageX: 0pageY: 0path: Array[16]repeat: falsereturnValue: trueshiftKey: falsesrcElement: atom-text-editor.editortarget: atom-text-editor.editortimeStamp: 1446634074596type: "keyup"view: Windowwhich: 16__proto__: KeyboardEvent
```

**Comment by sadovnychyi** [comment]
So for some reason your key code is 56, not 57. Maybe it's different on different locales, I'm not sure.
```
keyCode: 56
keyIdentifier: "U+0028"
```
But you do have same keyIdentifier like I do, maybe this is the right way to handle key events. 
I'll try to fix this tomorrow.

**Comment by walles** [comment]
I just found this info about `keyCode`:
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

```
This feature has been removed from the Web standards. Though some browsers may still support it, it is in the process of being dropped. Do not use it in old or new projects. Pages or Web apps using it may break at any time.
```

So using `keyIdentifier` instead sounds reasonable :).

**Comment by sadovnychyi** [comment]
Yeah, I'll fix it. It's probably makes sense to add a command in atom to complete arguments manually. So you can set a hotkey for it if you want. Just like for go-to-definition.

**Comment by sadovnychyi** [comment]
Fixed! Also added a command to trigger completions manually.You can bind that command to a hotkey if you want.
![sample](https://cloud.githubusercontent.com/assets/193864/10960299/6faf4072-83be-11e5-8304-569136da58d7.gif)
