### ISSUE TITLE
Insane memory footprint

### ISSUE THREAD

**Issue by lordnynex** [sadovnychyi/autocomplete-python#114]
after working for a few hours I glanced over at conky and realized autocomplete-python has allocated 1GB of memory! Thats insane. Is this intentional caching? Is this a leak? 

Might I suggest an LRU cache instead?

**Comment by sadovnychyi** [comment]
Python process does only communication with Jedi, I cannot fix any memory leaks there.
All caching is done on Jedi side as well. You actually can kill this process and new one will be spawned when you will use completions. Maybe we could do it automatically.

**Comment by sadovnychyi** [comment]
Closing this in favor of #112.
