### ISSUE TITLE
provider.coffee: why use onDidChangeGrammar?

### ISSUE THREAD

**Issue by dragonxlwang** [sadovnychyi/autocomplete-python#116]
I'm having trouble to use parameter autocomplete: it can only be enabled if I select grammar from non-python to python. That is, if the file is already seen by atom as python, then parameter autocomplete won't work! I tried to dig into the problem in the file provider.coffee, and I found the Ln 96 suspicious:

```coffee
editor.displayBuffer.onDidChangeGrammar (grammar) =>
        eventName = 'keyup'
        eventId = "#{editor.displayBuffer.id}.#{eventName}"
        @_log 'BREAKPOINT', eventId
        if grammar.scopeName == 'source.python'
          disposable = @_addEventListener editor, eventName, (event) =>
            if event.keyIdentifier == 'U+0028'
              @_completeArguments(editor, editor.getCursorBufferPosition())
          @disposables.add disposable
          @subscriptions[eventId] = disposable
          @_log 'Subscribed on event', eventId
        else
          if eventId of @subscriptions
            @subscriptions[eventId].dispose()
            @_log 'Unsubscribed from event', eventId
```

Could you please let me know why you use onDidChangeGrammar? What does it really mean? (I have almost zero knowledge in coffee script so I can only guess this is the reason that autocomplete for parameter only work after grammar change)...

Upd:

and after playing around with your code and try a few tricks, I found the following change works for me so far. Please let me know if this has any potential problems

```coffee
atom.workspace.observeTextEditors (editor) =>
      eventName = 'keyup'
      eventId = "#{editor.displayBuffer.id}.#{eventName}"
      if editor.getGrammar().scopeName == 'source.python'
        disposable = @_addEventListener editor, eventName, (event) =>
          if event.keyIdentifier == 'U+0028'
            @_completeArguments(editor, editor.getCursorBufferPosition())
        @disposables.add disposable
        @subscriptions[eventId] = disposable
        @_log 'Subscribed on event', eventId
      else
        if eventId of @subscriptions
          @subscriptions[eventId].dispose()
          @_log 'Unsubscribed from event', eventId
```
Cheers

**Comment by sadovnychyi** [comment]
Atoms default grammar is null, so when you load python file its getting
changed to python. In beta, at least. Maybe behavior is different in stable
for now.

**Comment by dragonxlwang** [comment]
I hate to reply late and bring it up again... just to get it clear: so even if a .py file will be loaded first as plain text and then atom will change its grammar to python so that it can active the parameter completion? I saw your reply in post #100 that it seems you set it such that only when changing the grammar by user will enable argument completion. But on stable version 1.2.4, anyways, it seems that when loading a python file (*.py), the onDidChangeGrammar event is never called. Maybe we should add test " if grammar.scopeName == 'source.python'" as well so that it covers both cases (new a py file and load existing py files)?

**Comment by sadovnychyi** [comment]
I'll check it on stable. My bad I was checking it only on beta.

**Comment by sadovnychyi** [comment]
Fixed it! Now should work on both stable & beta.

**Comment by dragonxlwang** [comment]
Thanks!

Best Regards!

—
Xiaolong,
