### ISSUE TITLE
support per-project python executables/packages

### ISSUE THREAD

**Issue by tony-garcia** [sadovnychyi/autocomplete-python#120]
I usually have each python project in its own virtualenv or conda environment. It would be great to be able to configure the python executable on a per-project basis (with projects as defined in the Project Manager package), sort of how the [Anaconda plugin for Sublime Text 3] (http://damnwidget.github.io/anaconda/#using-anaconda-per-project-config) works.

**Comment by sadovnychyi** [comment]
You can configure the packages to import by using $PROJECT variable, but not yet executable.

See #66.
