### ISSUE TITLE
ctrl + space for autocomplete suggestion appends end of string if no results are present

### ISSUE THREAD

**Issue by DarekDeo** [sadovnychyi/autocomplete-python#121]
For instance, while started typing random variable: groups
| - shows the place of the cursor

First situation (correct): g|roups
While cursor is after "g" of the string, it suggestes things to autocomplete as expected for "g"

Second situtation (wrong): grou|ps
Here autocomplete doesn't have any results to suggest for "grou", while pressing ctrl + space here it does this:
groups|ps
after pressing again:
groupsps|ps

pressing ctrl + space appends end of the string to the string.

I've disabled all plugins, left only autocomplete-python and problem was present, while disabling autocomplete-python plugin problem disappeard, so it looks like it is autocomplete-python related.

Tested on autocomplete-python 0.10.4 and 1.2.2 Atom. Not sure about different versions of Atom, haven't noticed it before, but I've also barely used this text editor.

**Comment by sadovnychyi** [comment]
Cannot reproduce on OSX.

**Comment by DarekDeo** [comment]
I have this problem on Linux, recorded a video: https://www.youtube.com/watch?v=yd3hOqKFqe4&feature=youtu.be

I am pressing ctrl + space when first autocomplete appears and when chars are being added to the string. At the end of the video I've tried to press ctrl + space few times but nothing happend (expected behavior).

**Comment by sadovnychyi** [comment]
Hmm, is this is what you mean?

![sample](https://cloud.githubusercontent.com/assets/193864/11387904/b6348bea-936a-11e5-9e7f-6adc3b0d24d7.gif)

It is not going to remove anything *after* cursor. So it's likely to be expected behaviour.

**Comment by DarekDeo** [comment]
Yes, this is what I mean. While using only autocomplete-plus it does nothing at this situation. Maybe python plugin should check if variable/method is already typed before appending it's end or maybe I am just terribly wrong. :)

**Comment by sadovnychyi** [comment]
Yeah, I agree that built in providers are smarter in this case, they will modify suffix as well.

Cannot say when I'll be able to fix this though. PRs are welcome!

**Comment by sadovnychyi** [comment]
In order to fix this we need to use "text" instead of "snippet" [here](https://github.com/sadovnychyi/autocomplete-python/blob/master/lib/completion.py#L123), but it may cause issues with fuzzy matcher as mentioned in #90.

**Comment by sadovnychyi** [comment]
![sample](https://cloud.githubusercontent.com/assets/193864/11584141/4961099c-9a9c-11e5-9692-07c8bec18ce4.gif)
Fixed!
