### ISSUE TITLE
Multiple python processes running with 50% cpu usage

### ISSUE THREAD

**Issue by dessant** [sadovnychyi/autocomplete-python#123]
After some light usage of Atom 1.2.4 with autocomplete-python 0.10.6 and py3.4 on win10 x64, multiple python processes appear over time, some of them are running with constant ~50% cpu usage, even if the editor is stopped being used and it is minimized. CPU hogging has been present before with this plugin, but now it also replicates. :stuck_out_tongue:

@sadovnychyi i have seen your recent efforts related to this, first restarting the process after 1k calls, then restarting every 30 minutes, but those measures do nothing when the untraced bug happens to hit just after a few minutes.

Have you thought about asking the help of jedi and atom core devs? Maybe they could offer some advice on how to find and fix the real cause of the bug.

**Comment by sadovnychyi** [comment]
I would have more chances to fix it if I could reproduce it. It never happened for me on OSX, but it does spawn process for each window though. This is something I could fix but just not in my priority list for now. I always keep couple of Atom windows open and they kill by battery as crazy.. That's why I decided to at least kill them after 30 mins.

@davidhalter can you give us any advices why jedi can eat so much CPU/memory sometimes?

**Comment by dessant** [comment]
I only use one window and the processes appear after some time regardless.
Btw, I've also seen a process starting eating cpu *after* i've let it sit 10-20 minutes, and it looked healthy at the time i've stopped using the editor. Once the bug sets in, the process never sleeps again, until killed.

I don't have experience with atom debugging, but i would be glad to submit any trace you need, just tell me the steps.

**Comment by sadovnychyi** [comment]
Try to enable debug logs in package settings:
![image](https://cloud.githubusercontent.com/assets/193864/11466486/2bd2322a-977c-11e5-8c88-721a333105a7.png)

And then after issue occurs look in developer tools console for something from this package:
![image](https://cloud.githubusercontent.com/assets/193864/11466471/145c7e0c-977c-11e5-80a5-d0d363dad0be.png)
Any python tracebacks with errors? Any communication with python process when you are not trying to autocomplete something?

**Comment by davidhalter** [comment]
> @davidhalter can you give us any advices why jedi can eat so much CPU/memory sometimes?

It's pretty easy: Python code can be very complicated. So understanding it can be a very long task. This is something that cannot be fixed, really. What we should do is to move towards an async server structure that allows stopping calls after a certain while.

~ Dave

**Comment by sadovnychyi** [comment]
Seems legit, thanks for answer. I'll try to implement request timeout in
near future.

**Comment by dessant** [comment]
> Python code can be very complicated. So understanding it can be a very long task. This is something that cannot be fixed, really.

@davidhalter, i would prefer to try understanding the bug and at least look at an error log before concluding that it is unsolvable.

**Comment by dessant** [comment]
@sadovnychyi i've activated provider errors and i've got this:

```python
Traceback (most recent call last):
  File "C:\Users\prc\.atom\packages\autocomplete-python\lib/completion.py", line 257, in watch
    self._process_request(self._input.readline())
  File "C:\Users\prc\.atom\packages\autocomplete-python\lib/completion.py", line 226, in _process_request
    request = self._deserialize(request)
  File "C:\Users\prc\.atom\packages\autocomplete-python\lib/completion.py", line 201, in _deserialize
    return json.loads(request)
  File "e:\dev\envs\py34_x86\Python\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "e:\dev\envs\py34_x86\Python\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "e:\dev\envs\py34_x86\Python\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

This traceback keeps being repeated, keeping the python process busy, and also freezing atom if showing provider errors is ticked. The editor was not used at the time the error appeared.

**Comment by dessant** [comment]
@sadovnychyi as for the multi process issue, when a new tab is opened, a new process is started and immediately closed, but some of them stay there.

**Comment by sadovnychyi** [comment]
It seems like python's daemon receiving empty string all the time causing infinite loop. This is something I can fix. Also, I could check if there are any python process spawned already – and try to re use it, instead of spawning new one. I'll take a look on this hopefully this week.

**Comment by patrys** [comment]
I'd rather look into terminating processes for projects without focus. Reusing processes is hard when each project can depend on a different interpreter.

**Comment by dessant** [comment]
@patrys this is just on project, with 2-3 files opened in different tabs.

@sadovnychyi Thanks a lot for looking into this.

**Comment by sadovnychyi** [comment]
@patrys Agree, but the best solution is to keep one process per
project/config.

**Comment by sadovnychyi** [comment]
@dessant is there are any "Serializing request to be sent to Jedi" values before python traceback? JSON value sent by Atom seems to be corrupted, so I would like to see that value.

**Comment by davidhalter** [comment]
> > Python code can be very complicated. So understanding it can be a very long task. This is something that cannot be fixed, really.
> 
> @davidhalter, i would prefer to try understanding the bug and at least look at an error log before concluding that it is unsolvable.

I have no idea about the issue here. I'm just saying that very rarely Jedi's type inference takes a few seconds.

~ Dave

**Comment by sadovnychyi** [comment]
Turned out that there are no easy way to share objects between multiple windows. Without this I cannot prevent it to spawn multiple processes. Does anybody can help?

**Comment by dessant** [comment]
I've activated debug logging, but there's no mention of values sent by atom. What we do know is that the exception seems to happen at process timeout.

![untitled1](https://cloud.githubusercontent.com/assets/7513068/11540128/c20db18e-9933-11e5-84ad-2f9ac7653b1e.png)

**Comment by dessant** [comment]
@sadovnychyi a different thing which should be tackled, unless setting provider errors to be shown, this exception does not show a popup, despite being a critical error and originating from `completion.py`, not the provider itself, jedi. This results in bugs being harder to discover and report.
Why the exception is repeated in an infinite loop is not clear either.

Should I open a different issue for this?

**Comment by sadovnychyi** [comment]
There's no message about re spawning the process. Strange. So its not
getting killed properly? I need to test it on windows.

**Comment by sadovnychyi** [comment]
@dessant confirmed. Just reproduced it on windows. Trying to fix it.

**Comment by sadovnychyi** [comment]
CPU usage while you don't use it should go away, nothing I can do with multiple processes for now though. It should use one process per window. If you don't use completions for 10 mins in specific window -- process will be killed.
