### ISSUE TITLE
New processes are being spawned and killed

### ISSUE THREAD

**Issue by dessant** [sadovnychyi/autocomplete-python#127]
With autocomplete-python 1.0.3, I'm opening a tab and typing something, the first python process appears.
For every single autocompletion request that comes next, a new python process is spawned and killed, while one is already running. The exact same behavior can be seen when a new tab is opened with a python file, a process starts and exits, while one is already there.

There is no mention of spawning new processes after the first one in debug logs, please look at your process list as you type and you should see the processes popping up. Tested on Windows.

**Comment by dessant** [comment]
Ok, this one seems to be caused by a flake8 plugin instead, my bad. :P

**Comment by sadovnychyi** [comment]
Yeah, flake8 just spawn s process for single check, while autocomplete-python keep one running all the time when you use it. It will be killed after 10 minutes of inactivity and respawned automatically when you will use it.
