### ISSUE TITLE
Does not show parameters in the correct way and too long description

### ISSUE THREAD

**Issue by rugk** [sadovnychyi/autocomplete-python#128]
Just compare this package with [autocomplete-php] and you'll see that the parameters in fact should be shown as parameters and not in the description part:
![parametershow](https://cloud.githubusercontent.com/assets/11966684/11576411/c56adbf2-9a16-11e5-842b-0a653fb0367a.gif)
(left: PHP; right: Python)

So please show the parameters in the correct way, so you can also use tab to switch between them and replace them.
Additionally the description often is a bit long and visually distracts if you switch between multiple multiple commands. Sometimes this even causes the field to jump from the top to the bottom:
![longdescription](https://cloud.githubusercontent.com/assets/11966684/11576618/428ec4a8-9a18-11e5-9909-ba4402348fbd.gif)

**Comment by patrys** [comment]
If you open parenthesis you will get the parameters completed (assuming it's enabled in package settings). Completing them the way php plugin does would prevent you from passing a function as a parameter without actually calling it.

**Comment by sadovnychyi** [comment]
Yeah, in python you don't always want to complete function with parameters, so we complete them only after a parenthesis character and this is still optionally. And you can jump between arguments using tab.

What's your proposed solution for long doc strings? You can disable them at all, not sure that there's should be a way to cut them off. I'm sure you can edit your stylesheets to hide it under a scrollbar.

**Comment by rugk** [comment]
> If you open parenthesis you will get the parameters completed (assuming it's enabled in package settings).

Oh, You mean the setting "Autocomplete Function Parameters"? I've set it too "all", but even after adding a bracket nothing autocompletes there.

> Yeah, in python you don't always want to complete function with parameters, so we complete them only after a parenthesis character and this is still optionally. 

Okay, this makes sense.

> What's your proposed solution for long doc strings? You can disable them at all, not sure that there's should be a way to cut them off. I'm sure you can edit your stylesheets to hide it under a scrollbar.

A scrollbar may be one way. Another way would be to truncate the description so that it has (nearly) the same height for every command and add a link "Show more..." or something similar where you can show the rest when you click on it.

**Comment by sadovnychyi** [comment]
>  I've set it too "all", but even after adding a bracket nothing autocompletes there.

Can you enable debug logs in settings, try to complete something with it and show me those logs?
