### ISSUE TITLE
Does not support all default modules

### ISSUE THREAD

**Issue by rugk** [sadovnychyi/autocomplete-python#129]
E.g. it does not seem to support `string`:
![nostringpreview](https://cloud.githubusercontent.com/assets/11966684/11576698/ec9d9f78-9a18-11e5-8f17-4b8d59362897.gif)

Example from: http://pythoncentral.io/pythons-string-replace-method-replacing-python-strings/

**Comment by sadovnychyi** [comment]
![image](https://cloud.githubusercontent.com/assets/193864/11582271/8976991c-9a87-11e5-866c-2a24f5c46ae3.png)

What exactly do you mean? I can get completions for "string" package.

**Comment by rugk** [comment]
> What exactly do you mean? I can get completions for "string" package.

I don't. That's the issue.

![noautocompletion](https://cloud.githubusercontent.com/assets/11966684/11610109/1247b69c-9b99-11e5-88b6-a4d257fb2c3f.png)


autocomplete-python v1.2.0
Python 3.4.2
Atom 1.2.4
Windows 7 x64

**Comment by rugk** [comment]
Ah I just used the wrong syntax. Maybe due to a new python version or whatever, but by using the variable as a kind of object it works:
```python
str = "this is string example....wow!!! this is really string"
print(str.replace("is", "was"))
```
