### ISSUE TITLE
Suggestion after space

### ISSUE THREAD

**Issue by dmbasso** [sadovnychyi/autocomplete-python#131]
I find this "feature" extremely annoying, and would really like to have the option to disable it. I've changed the offending code in my own installation, but I'd be willing to provide a patch with the option added.

My change:
```coffeescript
  getSuggestions: ({editor, bufferPosition, scopeDescriptor, prefix}) ->
    if prefix != '.' and (prefix.length < 1 or /\W/.test(prefix))
      return []
```
instead of `if prefix in ['.', ' ']`. Adding it as an option is trivial.

Thanks for the package, it is (annoying "feature" notwithstanding) very nice.

**Comment by sadovnychyi** [comment]
Added an option.

You going to use something like "([\.]|[a-zA-Z_][a-zA-Z0-9_]*)"

**Comment by dmbasso** [comment]
It's working great, thank you very much. There is one odd behavior, though, that is not important enough to deserve its own issue, so I'll mention it here. Suppose you're typing:

```python
log = logging.getLogger(__name__)
log.
```
After the dot it will correctly suggest `addFilter`, `addHandler`, etc. Then you type space and it should still give you the same suggestions, but it gives you the annoying suggestions `abs`, `all`, `and`, `any`, etc. Btw, I call them annoying because they're so completely out of context that the probability of them being the appropriate suggestion is close to zero. They're just interference.

Anyway, this is a minor issue, don't waste too much thought on it.

**Comment by sadovnychyi** [comment]
While `log. something` looks like valid python code I don't think that I can fix this.
As for me suggestion on space useful on imports when you type something like `from foo import` and hit space you can see what exactly you can import. And its still useful to complete local variables after "=" for example. 
```
foo = 1
bla = # foo getting completed here
```

**Comment by patrys** [comment]
We could check whether the last non-space character is a dot and then ignore the whitespace entirely.

**Comment by dmbasso** [comment]
> As for me suggestion on space useful on imports

I agree on that. I'll try to come up with a regex/code patch to allow that case. Let's hope it doesn't get too computationally expensive.

> And its still useful to complete local variables

Yes, that could be useful. But it seems in my case it gets the suggestions from the entire list of possible strings, not just the local scope. Would there be something wrong with my installation? Either way, perhaps a good option to have would be "disable suggestions if list is bigger than the population of earth", or something.

**Comment by sadovnychyi** [comment]
> I'll try to come up with a regex/code patch to allow that case.
You cannot do it by simply modifying regexp – since not the entire line is passed to it, only prefix provided by autocomplete-plus. This will require some additions to pass entire line.
> But it seems in my case it gets the suggestions from the entire list of possible strings, not just the local scope.
You mean the things like `abs`, `all`, `and`, etc? They are actually correct values from global scope.

**Comment by dmbasso** [comment]
> You mean things like abs, all, and, etc? They are actually correct values from global scope.

Not only from the global scope, `and` is a keyword, that's why I said "possible strings" (I meant valid, not "the language spanned by [a-z...]+"). Sure they are correct/possible, and the chance of me wanting to use them is close to zero. It would be better if the list were ordered with the most frequently used first, but a list containing a bazillion unordered items is useless.

**Comment by sadovnychyi** [comment]
I agree with you, but nothing I can do about it for now.

**Comment by dmbasso** [comment]
No worries, I'm pretty satisfied with the current version. Again, thank you for all your work.

**Comment by fakeycakez** [comment]
Hey guys, just thought you should know. dmbasso is a pedophile. I would not have anything to do with this sick fuck.
http://slashdot.org/comments.pl?sid=8718363&cid=51458573
