### ISSUE TITLE
Shows doc of own file in import dialog

### ISSUE THREAD

**Issue by rugk** [sadovnychyi/autocomplete-python#133]
![showdecr](https://cloud.githubusercontent.com/assets/11966684/11610998/37f4ba2a-9bb7-11e5-9a03-d810962e3b4e.PNG)

I think this is not what it is supposed to be.

**Comment by sadovnychyi** [comment]
Filled bug in Jedi, please track it there.

https://github.com/davidhalter/jedi/issues/656
