### ISSUE TITLE
Always uses /usr/bin/python

### ISSUE THREAD

**Issue by M0rtenB** [sadovnychyi/autocomplete-python#134]
My Python script starts with the line "#!/usr/local/bin/python3". From the error log I can see that autocomplete-python finds all my Homebrew-installed python executables, including python3, but it always chooses "/usr/bin/python". Changing the "Python Executable Paths" setting doesn't do anything, and the "Path to Python Directory" setting mentioned on the homepage doesn't exist.

Is this a bug or have I missed something?

**Comment by sadovnychyi** [comment]
`Path to Python Directory` setting were removed, sorry for confusing in docs, I'll remove it from there as well. What did you pass to `Python Executable Paths`? It should be entire path to python executable including executable name. (so should end with something like `python` or `python3`. Can you enable debug logs and look for something like `User defined interpreters found/not found`?

And I actually forgot about file header to look for executable path. We could give higher priority for binary provided in file header.

**Comment by M0rtenB** [comment]
I get the same results whether my `Python Executable Paths` is left alone, set to `/usr/local/bin/python3` or set to `/usr/local/Cellar/python3/3.5.0/bin/python3` (the former is a symlink to the latter). I restart Atom between each attempt.

The log goes:

```
Spawning python process...
No user defined interpreter found, trying automatic lookup
Project level interpreters found Set {}
Total automatically found interpreters Set [...]
<entries>[8]
0: "/usr/bin/python"
1: "/usr/bin/python2.6"
2: "/usr/bin/python2.7"
3: "/usr/local/bin/python"
4: "/usr/local/bin/python2"
5: "/usr/local/bin/python2.7"
6: "/usr/local/bin/python3"
7: "/usr/local/bin/python3.5"
Using interpreter /usr/bin/python
```
It obviously succeeds in locating a python3 interpreter. This leaves at least two questions:
* How does it decide which interpreter to use?
* Why is the `Python Executable Paths` not recognized?

**Comment by sadovnychyi** [comment]
`No user defined interpreter found, trying automatic lookup` means that lookup of `/usr/local/bin/python3` failed for some reason. It checks if provided file is executable and you can access it. Looks like this check failed. Automatic lookup simply chooses the first one, currently there's no any priorities. 

Can you add a couple of log statements?
https://github.com/sadovnychyi/autocomplete-python/blob/master/lib/interpreters-lookup.coffee#L63 `log.debug 'userDefinedPythonPaths', userDefinedPythonPaths`
https://github.com/sadovnychyi/autocomplete-python/blob/master/lib/interpreters-lookup.coffee#L41 and here for both true false

Then you should be able to see why it cannot find executable provided by you in the setting,

**Comment by M0rtenB** [comment]
Now I don't know much about Coffeescript, but somehow using .length instead of .size solves the problem!

**Comment by sadovnychyi** [comment]
Oh, thanks for catching this. Fixed now!
