### ISSUE TITLE
Ability to go back after go-to-definition

### ISSUE THREAD

**Issue by muffinmad** [sadovnychyi/autocomplete-python#136]
Is there any way to go back to code where go-to-definition function was called from?

**Comment by sadovnychyi** [comment]
No, nothing like this has been implemented. Have any ideas?

**Comment by muffinmad** [comment]
In general:
1. Push current editor position to some stack list before jumping to definition.
2. Function that pop editor position from that stack list and jump to it.

I can't code it and can't tell if it possible at all because i'm not familiar with hacking atom yet.

**Comment by sadovnychyi** [comment]
That's sounds doable. And activating by separated command like "go back
from definition" with optional hotkey. I can implement it likely next week.

**Comment by muffinmad** [comment]
Cool. And maybe SelectListView with jumps positions?
Thanks!

**Comment by sadovnychyi** [comment]
What do you mean by selectlistview with jump positions?

**Comment by muffinmad** [comment]
List like "Command Palette" wich contains stack list of editor positions populated by go-to-definition function.
For example if one jump from line `class A(B):` in file1.py to definition of class B in file2.py and than to definition of class C in file3.py than that list would be look like:
```
---
class B(C):
file2.py
---
class A(B):
file1.py
---
```
So one can go back from definition to any jump without need to pop editor positions from jumps stack list one by one.

**Comment by sadovnychyi** [comment]
OK, so basically keep N items in history, right?

**Comment by muffinmad** [comment]
Yes. And also remove item from history on go-back.

**Comment by patrys** [comment]
I'd like to point out there are atom packages that already provide this functionality. No need to duplicate the effort in autocomplete-python. There's also this: atom/symbols-view#70

**Comment by sadovnychyi** [comment]
@patrys that seems like dead issue. Somebody would need to pick up that [PR](atom/symbols-view/pull/95) and continue its implementation.

**Comment by rajalokan** [comment]
Do we have this feature in autocomplete-python now? What is the best way to get this. 
Thanks in Advance.
