### ISSUE TITLE
suggest:do like pycharm argument tips

### ISSUE THREAD

**Issue by Javacym** [sadovnychyi/autocomplete-python#137]
![image](https://cloud.githubusercontent.com/assets/13167757/11684603/c0ba5c72-9ead-11e5-9bb8-1c87b61b8428.png)
but atom not tips:
![image](https://cloud.githubusercontent.com/assets/13167757/11684646/1a4ede5c-9eae-11e5-8297-212732d814af.png)

**Comment by sadovnychyi** [comment]
It's currently implemented in this way:
![sample](https://cloud.githubusercontent.com/assets/193864/11684852/83513520-9eaf-11e5-85f6-a54fef4645fb.gif)

Argument completion and docstrings. It may be useful to implement what you suggesting, but it will require building an UI for that. I don't think that I want to do this.

You are welcome to implement this by yourself though!

**Comment by Javacym** [comment]
Ok,and is there a way show docstring on right not on buttom?

**Comment by sadovnychyi** [comment]
Nope, it's not supported by autocomplete-plus. But I'm sure you can edit your own stylesheet to move it to the right.

**Comment by sadovnychyi** [comment]
As an option we could display list of current arguments in [status-bar](https://github.com/atom/status-bar). But this will require watching cursor movement events.

**Comment by sadovnychyi** [comment]
Related to atom/atom#9936

**Comment by Javacym** [comment]
I suggest:
1. autocomplete parenthesis ,like :str.split--->str.split() ,
2.then,cursor in parenthesis, do like linter package:
![image](https://cloud.githubusercontent.com/assets/13167757/11710817/f28ca0b6-9f5c-11e5-97ca-d8701ee8e081.png)

**Comment by sadovnychyi** [comment]
@Javacym you don't always want to actually *call* function. No need to automatically complete parentheses.

**Comment by Javacym** [comment]
@sadovnychyi ,if i don't want it,i just delete parentheses use backspace key,it quicker than use shitf+( to add parentheses....but i think most times,i want to call a function
