### ISSUE TITLE
Suggestions after import keyword (from x import y)

### ISSUE THREAD

**Issue by Alexx-G** [sadovnychyi/autocomplete-python#138]
I'm talking about the use case when I wrote `from x import ` and I want to receive list of all available items from the module *x*.
It works when I start typing, but space after the `import` keyword doesn't trigger autocomplete. Actually it triggers (at least prints in devtools), but doesn't provide any suggestions.

Atom version: 1.2.4
autocomplete-python: 1.2.2
Python: 3.4.2

I'm using this package with default settings.

**Comment by sadovnychyi** [comment]
Looks like its broken with fuzzy search turned on. Works without it.
Will fix it soon.
