### ISSUE TITLE
JavaScript console opens when reloading Atom

### ISSUE THREAD

**Issue by caleb531** [sadovnychyi/autocomplete-python#14]
Hi,

I've noticed that when this package is enabled and I reload Atom (via the command palette or the respective key binding), the built-in developer tools opens on the *Console* tab. Disabling the plugin fixes the issue, but I'd really like to use this plugin. Can this be fixed?

Thanks,
Caleb

**Comment by sadovnychyi** [comment]
Should be fixed with 0.4.1. If it is not -- feel free to re-open this issue.
