### ISSUE TITLE
Failed to load the autocomplete-python package. At Cannot find module 'atom-slick'

### ISSUE THREAD

**Issue by morning-color** [sadovnychyi/autocomplete-python#142]
I've got a problem when I tried to install autocomplete-python package, the informations are as follow:

**Atom Version**: 1.2.4
**System**: Ubuntu 14.04.1
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v1.2.3

### Stack Trace

Failed to load the autocomplete-python package

```
At Cannot find module 'atom-slick'

Error: Cannot find module 'atom-slick'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/zys/.atom/packages/autocomplete-python/lib/scope-helpers.coffee:1:9)
    at Object.<anonymous> (/home/zys/.atom/packages/autocomplete-python/lib/scope-helpers.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view",
      "build-tools",
      "git-control",
      "build",
      "builder",
      "terminal-status",
      "markdown-preview-plus",
      "tidy-markdown",
      "git-plus",
      "atom-innerspace",
      "whitespace",
      "file-bookmark",
      "python-tools"
    ],
    "packagesWithKeymapsDisabled": [
      "sync-settings",
      "git-control",
      "tree-view"
    ],
    "themes": [
      "one-dark-ui",
      "sublime-default-syntax"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-ctags, v4.4.1
autocomplete-clang, v0.8.8
autocomplete-python, v1.2.3
docblockr, v0.7.3
file-icons, v1.6.13
linter, v1.11.3
markdown-scroll-sync, v2.0.3
minimap, v4.17.0
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
sublime-default-syntax, v0.2.7
symbols-tree-view, v0.10.1
sync-settings, v0.6.0
tabs-to-spaces, v1.0.1
tree-view-open-files, v0.3.0

# Dev
No dev packages
```

Thanks!

**Comment by sadovnychyi** [comment]
```At Cannot find module 'atom-slick'```

You need to reinstall the package or do `apm install` inside of it.

**Comment by morning-color** [comment]
@sadovnychyi OK,thanks a lot!

**Comment by ashishmadeti** [comment]
Didn't work for me

**Comment by sadovnychyi** [comment]
@ashishmadeti try to completely remove the package and install it again, and/or try to run `npm install` inside of `~/.atom/autocomplete-python` folder.

**Comment by ashishmadeti** [comment]
Thank you very much, that worked!

On Sat, Mar 5, 2016 at 11:43 AM, Dmitry Sadovnychyi <
notifications@github.com> wrote:

> @ashishmadeti <https://github.com/ashishmadeti> try to completely remove
> the package and install it again, and/or try to run npm install inside of
> ~/.atom/autocomplete-python folder.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sadovnychyi/autocomplete-python/issues/142#issuecomment-192587273>
> .
>



-- 
*Ashish Madeti*
