### ISSUE TITLE
Help view doesn't scroll

### ISSUE THREAD

**Issue by yay** [sadovnychyi/autocomplete-python#148]
<img width="529" alt="screen shot 2015-12-23 at 10 50 48 pm" src="https://cloud.githubusercontent.com/assets/1799756/11985722/0bd1994e-a9c8-11e5-86c0-6a57d0e021de.png">

**Comment by sadovnychyi** [comment]
Looks like you have very small screen/resolution/windows size? I don't think that it's possible to have good default value here, so I suggest you to just modify your stylesheet with something like this:
```
atom-text-editor[data-grammar="source python"], :host {
  .autocomplete-suggestion-list.select-list.popover-list .suggestion-description {
    overflow-y: auto;
    max-height: 110px;
  }
}
```

**Comment by yay** [comment]
It a macbook (1440x900 equivalent). There is also another issue that is not an issue in PyCharm on that screen.

<img width="573" alt="screen shot 2015-12-24 at 8 12 36 am" src="https://cloud.githubusercontent.com/assets/1799756/11991121/b4182e58-aa16-11e5-8708-200b733b914e.png">

<img width="632" alt="screen shot 2015-12-24 at 8 13 39 am" src="https://cloud.githubusercontent.com/assets/1799756/11991123/b86f6b1a-aa16-11e5-88ee-d95c7272d773.png">

**Comment by yay** [comment]
After a quick check in web inspector I can confirm that this works, thanks! Although, I found 110px a bit to small. It would be good to have both the number of suggested results (currently 10) and the height of the help view configurable in the plugin's settings. It's not always possible to have a large display around.

**Comment by sadovnychyi** [comment]
If there's no space at the bottom to show completions – autocomplete-plus should move it above your cursor. You can check it by triggering completions list and scrolling up/down. This is exactly what pycharm doing in such case.

![sample](https://cloud.githubusercontent.com/assets/193864/11991218/ad695686-aa52-11e5-92aa-be61acc75d57.gif)

**Comment by sadovnychyi** [comment]
> After a quick check in web inspector I can confirm that this works, thanks! Although, I found 110px a bit to small. It would be good to have both the number of suggested results (currently 10) and the height of the help view configurable in the plugin's settings. It's not always possible to have a large display around.

Yes, that's why I said that it's hard to find good default value here, so you have to configure it by yourself. 
The whole completions list rendering is done by [autocomplete-plus](github.com/atom/autocomplete-plus) and you may want to check their settings.

![image](https://cloud.githubusercontent.com/assets/193864/11991266/44a5a928-aa53-11e5-9aa8-00bdcac14fae.png)

**Comment by yay** [comment]
Interesting... didn't know that. I just configured it just the way I like :) Thanks for your help!
As for the popup not flipping to the other side, I'm not sure why it didn't work that time, works just fine now.

**Comment by sadovnychyi** [comment]
Ok, glad to help! FYI I use Atom with same 1440x900 equivalent and it's comfortable for me. There's other autocomplete providers so you may want to apply those changes globally by removing grammar filter in CSS rule.
