### ISSUE TITLE
Virtualenv functionality seems not to be working

### ISSUE THREAD

**Issue by revernus** [sadovnychyi/autocomplete-python#149]
This extension seems not to be working concerning the virtualenv functionality. I've installed it and I think I've set it right. Under "Python Executable Path" I put "$PROJECT/env/bin/python;/usr/bin/python" and under "Extra Paths For Packages" I put "$PROJECT/env/lib/python2.7/site-packages". My virtualenv is under $PROJECT/env and still Atom pylinter will say it couldn't import flask because it's not installed in the main python env, though it's installed in the local project "env" folder. I've closed and reopened Atom multiple times also. Nothing seems to work. Could someone help me, please?

**Comment by revernus** [comment]
Here is a print screen: http://i.imgur.com/cQcsPuo.png

You can see on the tree panel that I have an "env" folder, which has flask installed. In the left panel you can see I've put this "env" folder in the settings. Still, in the right panel you can see there is an error saying flask couldn't be imported, probably because this "env" folder is not visible to Atom, as it should be.

**Comment by revernus** [comment]
One last thing. Even when Atom is launched from a terminal window in which this virtual environment is active, the error persists, saying it couldn't import flask. But everything is working just fine, flask is being imported and my Flask App is running just fine from this virtual environment. Please help.

**Comment by sadovnychyi** [comment]
This package control only visibility of modules for autocomplete. This is separated from linter.
You should report this issue to the linter package you use.

**Comment by revernus** [comment]
Either I should report it here or you should remove this from the list of features:

- Automatic lookup of virtual environments inside of your projects

**Comment by revernus** [comment]
I don't think my report is invalid. Rather, the feature you said this extension had is invalid.

**Comment by sadovnychyi** [comment]
It does lookup your virtual environments automatically and makes them available for **autocompletions**.
