### ISSUE TITLE
Some settings from autocomplete-plus not being honored?

### ISSUE THREAD

**Issue by Osmose** [sadovnychyi/autocomplete-python#15]
I dunno if this is a bug in autocomplete-plus, a bug in autocomplete-python, or me misunderstanding how the setting is supposed to work. I have `autocomplete-plus` set to not suggest anything until I've typed at least 1 character, yet I still get suggestions in Python when I haven't even typed the first letter in a word:

![screen shot 2015-05-26 at 1 51 06 pm](https://cloud.githubusercontent.com/assets/193106/7823111/4b9ae848-03ae-11e5-80af-5558a5f3da2b.png)

Having all the built-ins and local variables being suggested before I've even typed anything isn't terribly useful, especially if I try to move the cursor up or down. Any ideas on how to fix this?

**Comment by sadovnychyi** [comment]
There's an issue filled already in autocomplete-plus: atom/autocomplete-plus#335
While I can manually read the config from the autocomplete-plus and do not trigger the autocompletions, I don't think that this is the right thing to do. Let's wait a bit and see if that issue will move forward.

**Comment by Osmose** [comment]
Ohhh, nice find. I'll watch that thread. Thanks for the help!
