### ISSUE TITLE
Import is not definition

### ISSUE THREAD

**Issue by syabro** [sadovnychyi/autocomplete-python#154]
Dmitriy, is it possible to go to the actual definition instead of import line?
It's how PyCharm does and it's more useful — in most cases you'll need to check the original file, instead of how this class/function/variable was imported.

PS Все еще в коворкинге обитаешь? 😊

**Comment by sadovnychyi** [comment]
Agree, I often click twice to get into actual sources. We probably can run goToDefinition recursively until there are no matches found. It may be slow for long import chains though. Will take a look!

*отсюда же и пишу :)*

**Comment by patrys** [comment]
I'll take a look at this. I think we can tell whether a definition is an import declaration or not.

**Comment by sadovnychyi** [comment]
@patrys https://github.com/sadovnychyi/autocomplete-python/pull/155 here's what I got. Thoughts?

**Comment by patrys** [comment]
I was thinking the same. :+1:

**Comment by sadovnychyi** [comment]
It's live now with 1.3.0 with some extra additions.
