### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by k4nar** [sadovnychyi/autocomplete-python#157]
First, thank you for making this awesome package!

I'm using it for quite some time now, and every time I see an update I go to the commit log to see the changes. I guess it would be simpler for the users if there was a Changelog somewhere highlighting the main changes.

It would help users to never miss new features.

**Comment by sadovnychyi** [comment]
Not sure that I will be able to explain something better than inside of commits, but I'll try to add simple CHANGELOG.md and update it on each new release.

With today's updates I've fixed go to definition [behaviour](https://github.com/sadovnychyi/autocomplete-python/issues/154) and added show usages command which is explained with GIF [here](https://github.com/sadovnychyi/autocomplete-python/pull/156).

**Comment by k4nar** [comment]
That would be grand, thank you!

**Comment by sadovnychyi** [comment]
https://github.com/sadovnychyi/autocomplete-python/releases – will try to mantain it here for at least new features.
