### ISSUE TITLE
Access Python env in a Vagrant box

### ISSUE THREAD

**Issue by richarddewit** [sadovnychyi/autocomplete-python#158]
Is it possible (or could it be made possible) to access the Python env in a Vagrant box? This is the only thing from stopping me to switch entirely to Atom.

**Comment by sadovnychyi** [comment]
I've never used it. Can you explain a little bit? What do you use right now?

**Comment by richarddewit** [comment]
I use PyCharm now, I can connect to the Vagrant host and it gets the Python interpreter there:

<img width="480" alt="screen shot 2016-01-13 at 2 32 05 pm" src="https://cloud.githubusercontent.com/assets/7933750/12295704/1796698a-ba03-11e5-9636-1e0c997bdadb.png">

**Comment by sadovnychyi** [comment]
Interesting. Do you have to configure it manually for each project? Atom does not have official per project configuration for now. But maybe we could extend `Path to python executables` setting to support `ssh://vargant@127.0.0.1:2222/usr/bin/python` like values.

I need to investigate about how to communicate with such interpreters from nodejs.

**Comment by sadovnychyi** [comment]
Is it true that each project that uses vagrant has a configuration file inside? Can we use it?

**Comment by richarddewit** [comment]
What it actually does is download the folder in a caching folder on the local machine, you have to set it up for each project.

Yes each project that uses Vagrant has a `Vagrantfile`, but that doesn't contain any of that information. And it's Ruby :weary:

**Comment by sadovnychyi** [comment]
Am I right that you keep your sources on local machine, but python environment with all installed dependencies inside of vagrant box? In this case, you keep your sources locally using synced folders, to keep sources on vagrant as well. Maybe it's easier to [configure](https://docs.vagrantup.com/v2/synced-folders/basic_usage.html) vagrant to sync venv folder as well?

Note that Atom may work with multiple roots in single project. This plugin will lookup virtual environments in all of them.

**Comment by richarddewit** [comment]
Yes, the sources folder is mapped to the Vagrant box' `/vagrant` folder.

I've looked into that, might worth a shot.

**Comment by sadovnychyi** [comment]
Any update on this?

**Comment by richarddewit** [comment]
When syncing the folder, the remote folder gets cleared before initial sync. So I had to reinstall the venv :) 

I'm now creating another venv inside the project (`projectroot/venv/`). This works but when I install a new package, I have to install it twice, locally an on the vagrant box. It's somewhat of a work around, but since I don't install new packages every day, it'll do.
