### ISSUE TITLE
autocomplete shows error all the time

### ISSUE THREAD

**Issue by can-z** [sadovnychyi/autocomplete-python#159]
Autocomplete is no longer working with this error message:

I use this plugin every day and it broke this morning (no significant changes outside Atom on my machine).

**Comment by can-z** [comment]
Looks like it could be a virtualenv issue. Will investigate before reopening if it is an issue with the plugin.

**Comment by sadovnychyi** [comment]
This is because of https://github.com/sadovnychyi/autocomplete-python/commit/cb44808134ed0993c8fbd1d94b38bd30c4a6dc95 – before all python related errors were hidden.
