### ISSUE TITLE
Autocomplete Functions Parameters should ignore *args and **kwargs

### ISSUE THREAD

**Issue by szastupov** [sadovnychyi/autocomplete-python#160]
I set "Autocomplete Functions Parameters" to "required" and quite happy with it, but it shouldn't insert `*args` and `**kwargs`.

**Comment by sadovnychyi** [comment]
Confirmed. I broke it in https://github.com/sadovnychyi/autocomplete-python/commit/a8bd701b24f65273d156d5205a334065968b7af1

**Comment by szastupov** [comment]
👍
