### ISSUE TITLE
Autocomplete Function Parameters does not work

### ISSUE THREAD

**Issue by exploide** [sadovnychyi/autocomplete-python#163]
Don't know if only I am affected but it seems that at least in my case *Autocomplete Function Parameters* does not work.

I configured autocomplete-python (1.4.3) to automatically complete required arguments. But they don't show up. Even in this simple example:
```python
def test_func(x, y):
    return x + y

a = 3
b = 6

test_fu.... # try it here
```

But when I trigger the complete-arguments command via palette, it works.

This is true for both, self written and standard library functions.

I also noticed that the *Add Bracket After Function*  and *Add Dot After Module* settings have no effect in my case. No bracket is inserted. Maybe related?!

Let me know if you need additional info.

**Comment by patrys** [comment]
Did you try opening a parenthesis after the function name? By default only the function name is inserted as functions themselves are often passed as values in Python.

**Comment by exploide** [comment]
Yes I tried. Did not work. Only when calling the command via palette explicitly.

**Comment by sadovnychyi** [comment]
Can you follow [this](https://www.reddit.com/r/Atom/comments/40p75p/how_to_highlight_a_functions_scope_and_how_to/) thread to try to resolve it?

**Comment by exploide** [comment]
Ah yes, same problem. On my keyboard (standard German) `(` produces this:
```
Identifier: U+0038
Code: 56
Char: 8
Modifier: shift
```

**Comment by sadovnychyi** [comment]
I'm not sure if I should just add another keyIdentifier or just introduce new setting to set it.
BTW `Add Bracket After Function` and `Add Dot After Module` were completely removed. Don't know why you still can see them.

**Comment by exploide** [comment]
Concerning the removed settings: Tried to reinstall autocomplete-python. Is it normal that the settings remain in config.cson after uninstall (actually I guess yes, because I found some leftovers from other packages as well. Don't like that behavior very much...)? But never mind, after I reinstalled autocomplete-python and removed the old settings from config.cson, the settings are gone and it looks as excepted.

Concerning the bracket issue: In my opinion, usability matters. So it would be nice if it works well out of the box, without the need of changing settings. But I understand that you like to keep the code clean. Personally, I would go with an additional keyIdentifier and hope that a better handling of keystrokes will eventually become available.

**Comment by sadovnychyi** [comment]
Will do it. I guess checking only for keyIdentifier would be enough, no need to check for shift.

**Comment by sadovnychyi** [comment]
Pushed 1.4.4 which should fix this.

**Comment by exploide** [comment]
nice, thanks!

**Comment by rumpelsepp** [comment]
This change is really annoying. When I type `print(` now, it expands to:

```python
print(value, sep=' ', end='n', file=sys.stdout, flush=False)
```

Please revert that.

**Comment by rumpelsepp** [comment]
Sorry for the noise, I have discovered the relevant config value. :)
