### ISSUE TITLE
No autocompletion for imported SciPy and Numpy

### ISSUE THREAD

**Issue by d3mueller** [sadovnychyi/autocomplete-python#169]
Hi

I imported SciPy and Numpy (and SymPy) but the plugin doesn't give me autocompletion. Is this a bug or just not supported?

Thank you.

Dennis

**Comment by sadovnychyi** [comment]
NumPy works well for me. Look on settings about python executable. 
![image](https://cloud.githubusercontent.com/assets/193864/12695397/b7c24258-c787-11e5-9580-42bd22e52629.png)
