### ISSUE TITLE
Minimum character setting not used

### ISSUE THREAD

**Issue by muppetjones** [sadovnychyi/autocomplete-python#17]
The default `Minimum word length` for `autocomplete-plus` is set to `3`, but `autocomplete-python` tries to complete with a minimum word length of `0`. For example, when writing any statement that ends in a colon, `abs` is predicted almost immediately, and I must hit `esc` before hitting return:

```python
def my_new_func():abs
  <cursor>
```

Perhaps more correctly, `autocomplete-python` seems to deem any number of characters after initial indentation as complete-worthy:

```python
def my_func():
  h <will pop_up suggestions here>
```

Although this is not a huge issue, it is fairly annoying. I didn't see any options to fix this in the settings either.

**Comment by sadovnychyi** [comment]
This is a duplicate of #15 which is related to atom/autocomplete-plus#335. As discussed in the original issue, it is possible to fix it just from the provider, but it will be a wrong way. We need to wait for autocomplete-plus to fix this issue. You will see the same issue with any autocomplete provider.

**Comment by muppetjones** [comment]
Thanks for the update!

**Comment by muppetjones** [comment]
Just as a side note...I disabled autocomplete-python, and the minimum-word-length works fine.

**Comment by sadovnychyi** [comment]
Did it broke the completion in other files as well, or only in python?

I made a small fix to ignore completions with zero length and on everything except letters, numbers, spaces and dots. It makes a lot of sense as for me to autocomplete on space. See the GIF.

![sample](https://cloud.githubusercontent.com/assets/193864/8348089/5e433e3c-1b41-11e5-88f5-5818768138ec.gif)

If you have any ideas about how to make it better (maybe configurable regex of allowed completions?) I'm glad to hear them.

**Comment by muppetjones** [comment]
Right now, I'm only working in python, but it looks like the minimum word length works for the base `autocomplete-plus`, even if that part of the api is not available/implementable for the plugins.

**That fix will help a ton! Thank you!** I'm not a huge fan of spaces, but seeing the gif, they make complete sense. I'll let you know if I have any ideas.

Side note: The gif appears to be fairly instantaneous. Is there a secret to having Atom run so smoothly?

**Comment by sadovnychyi** [comment]
I run it on macbook pro with 8 gb ram -- works pretty smooth for long time
already.

**Comment by sadovnychyi** [comment]
I'm closing this since I don't know what else to fix here. Feel free to create new issue if you get any ideas.
