### ISSUE TITLE
Is it possible to allow switch of "autocomplete function parameters" in drop-down menu?

### ISSUE THREAD

**Issue by dragonxlwang** [sadovnychyi/autocomplete-python#171]
In most cases such as using build in functions I don't want to have autocompletion for function parameters; but for some other functions like those I wrote or others I might like to have autocomplete-python do the work of filling arguments for me. It would be nice to allow choosing between those two cases in the drop-down menu when doing auto suggestion/completion. I know that I could get this done in static way in package settings or using command complete-arguments but it would be really helpful if one can choose directly in the drop-down menu on the fly...

**Comment by sadovnychyi** [comment]
Do you mean something like to duplicate each completion with arguments and without? Note that right now you can complete arguments one by one by starting typing it inside of function call.

```python

def foo(bar=None):
  pass

foo(b
```

you will get `bar` completed here.
