### ISSUE TITLE
Interferes with Atom multiple selection

### ISSUE THREAD

**Issue by jrial** [sadovnychyi/autocomplete-python#174]
Atom allows you to select multiple code regions by holding down CTRL while making multiple selections.

With this plugin enabled, holding down CTRL will turn all resolveable content into hyperlinks, on which the click-and-mark or double-click don't work the same way.

See https://youtu.be/fZEN35UdJWw for a demonstration.
* The first part of the video shows a normal workflow involving multi-select with aotocomplete-python disabled.
* Then I enable the plugin, undo my changes, and try again
* And immediately, you see that self can not be double-selected by holding down CTRL when double-clicking the 2nd instance, as it will jump to its "definition" in the arguments list at the top of my method. I forgot to demonstrate that click-and-mark doesn't work either, but I don't think reshooting the video is necessary as it's quite straightforward to reproduce.

**Comment by patrys** [comment]
Are you sure it's autocomplete-python and not [hyperclick](https://atom.io/packages/hyperclick)?

**Comment by jrial** [comment]
Sorry, you are correct, it's actually Hyperclick that does this. Filing a bug there.
