### ISSUE TITLE
Shows error that path could not be found on Windows

### ISSUE THREAD

**Issue by rugk** [sadovnychyi/autocomplete-python#177]
When editing a Python file this package shows me the following error:
![pythonerror](https://cloud.githubusercontent.com/assets/11966684/13029416/0aa6e578-d28c-11e5-89c9-14ea0c31e290.PNG)

The text is basically the default Windows error message, which is shown when an unknown command is executed (e.g. in cmd.exe):
![pythoncmd](https://cloud.githubusercontent.com/assets/11966684/13029450/00a6b002-d28d-11e5-954a-ef94e78d7202.PNG)

And `C:\Python34` is the path I set in the settings as Python is installed in this directory.
Note that this issue occurred in the latest or at least in one of the latest updates and AFAIK it worked before this update.

autocomplete-python v1.6.1
Atom 1.4.3 and 1.5.3
Windows 7 x64

**Comment by sadovnychyi** [comment]
After update you need to set path to python *executable*. So something like
`C:\Python34\python.exe`.

**Comment by rugk** [comment]
Okay, thanks. This way it works.
Did not know this.
