### ISSUE TITLE
Add functionality to put parent method with all needed parameters

### ISSUE THREAD

**Issue by pchomik** [sadovnychyi/autocomplete-python#178]
Hi,

First of all thanks for great plugin. 
As second I'd like to request new feature. In case of inheritance I'd like to override parent method. In current state I have to now what is a proper parent signature to do it well. It'd be nice to have some popup list with all methods from parents and add selected to current class.

I have seen such logic in pycharm and is very useful for me. 
I did not find example from pycharm but I found a page from Jetbrain and Java: https://www.jetbrains.com/idea/help/overriding-methods-of-a-superclass.html
The idea is very similar.

Is it possible to add such logic to your plugin?

**Comment by sadovnychyi** [comment]
Could you give me an example with some code?

Whether I can do it or not mostly depends on Jedi API. But I still want to understand what do you mean.

**Comment by sadovnychyi** [comment]
Hmm, so basically when we can use this while being inside of any class.

```python
class Foo(object):
  def test(self):
    return "foo"

class Bar(Foo):
  pass
```

Calling "override methods" inside of Bar gives us all possible methods of parent classes. 
When "test" is selected we will get something like:

```python
  def test(self):
    return super(Bar, self).test()
```

I will take a look if it's possible to achieve with Jedi.

**Comment by sadovnychyi** [comment]
Take a look on my pull request.

![sample](https://cloud.githubusercontent.com/assets/193864/13353709/1402e172-dcd1-11e5-9afa-b68b384fd5a0.gif)

**Comment by pchomik** [comment]
Great and fast work. That is exactly what I asked. Thanks
