### ISSUE TITLE
Error when upgrade (Atom 0.207)

### ISSUE THREAD

**Issue by mirac** [sadovnychyi/autocomplete-python#18]
exit with code null, signal SIGTERM

**Comment by sadovnychyi** [comment]
Is it still persists? Can you give me more information please?

**Comment by sadovnychyi** [comment]
I'm closing it, feel free to re-open if it still appears for you.

**Comment by mirac** [comment]
I think that plugins versions are mismatched. It was because of add-ons from the previous version.
