### ISSUE TITLE
Keep getting errors

### ISSUE THREAD

**Issue by Fufl0** [sadovnychyi/autocomplete-python#180]
Every time I type something I get these errors

autocomplete-python traceback output:
Traceback (most recent call last):
  File "C:\Users\Loren\.atom\packages\autocomplete-python\lib/completion.py", line 2, in ?
    import io
ImportError: No module named io

**Comment by sadovnychyi** [comment]
Make sure that [io](https://docs.python.org/2/library/io.html) library is avilable. I guess you need to use python 2.7 of higher.

**Comment by Fufl0** [comment]
I installed the last version, on mac works fine but on windows at home I still have problems. I'll try to look into it.

**Comment by aman0446** [comment]
I'm having the same issue. have installed python 3.6 through Anaconda. tried adding the path to environment variables(Windows PC)

**Comment by adilbari** [comment]
I am using Python 2.7.6 and windows10 having some issue: 

I assigned the project folder to  "/Users/sab/Desktop/Rooms" to project directory
Der Befehl "/Users/sab/Desktop/Rooms" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
