### ISSUE TITLE
Get Autocomplete-python working with autocomplete-plus

### ISSUE THREAD

**Issue by Nikowned** [sadovnychyi/autocomplete-python#183]
Hello, how to make Autocomplete-python working with autocomplete-plus , when i enable the package, i can't use some autocompletion from autocomplete-plus like def,class,for etc 

Do you have any solution ?

**Comment by sadovnychyi** [comment]
This plugin is an extension for autocomplete-plus. It shouldn't exclude any lower priority providers as from [here](https://github.com/sadovnychyi/autocomplete-python/blob/master/lib/provider.coffee#L15-L17).

It can however complete def, class, etc.
![image](https://cloud.githubusercontent.com/assets/193864/13394149/5ec7e692-df21-11e5-81f9-4e46cad6b2d0.png)

So what do you mean?

**Comment by Nikowned** [comment]
For example when autocomplete-python is disable def is not a "k purple" but a green arrow that created a template for a function same for class . So how can i choose between them ?

Thanks

**Comment by sadovnychyi** [comment]
I believe that completions with same name are removed by autocomplete-plus. Thus "def" which is snippet is replaced by "def" which is a keyword. One workaround for this is to define your own snippets with different name.

**Comment by sadovnychyi** [comment]
Another option is to set [this](https://github.com/sadovnychyi/autocomplete-python/blob/master/lib/provider.coffee#L15-L16) values to 0. Then autocomplete-snippets will have higher priority and will replace some completions from autocomplete-plus.
