### ISSUE TITLE
autocomplete-python traceback output: 'python' �����ڲ����ⲿ���Ҳ���ǿ����еĳ��� ���������ļ��� 

### ISSUE THREAD

**Issue by Alieas-PC** [sadovnychyi/autocomplete-python#188]
Hello, I just installed the autocomplete-python plugin, but it wasn't working properly. There's always a 'traceback' appeared on the left top of the panel like the screenshot below when I type a key. And the auto-completion didn't work.
Any ideas? Thanks for any help.

![image](https://cloud.githubusercontent.com/assets/11643943/13721382/3b0fba20-e860-11e5-9b63-d15140da7fb4.png)

**Comment by sadovnychyi** [comment]
You can try to enable debug logs in package settings and look on them in interactive console inside of developer tools. What is your system language? Any ideas about encoding problems? Did you try to set path to python executable in package settings? Your OS?

**Comment by Alieas-PC** [comment]
Thanks a lot for your reply, I've just solved this problem by setting up the python executable paths.
Thanks! :)
