### ISSUE TITLE
tkinter module not compleating

### ISSUE THREAD

**Issue by claudioarchi** [sadovnychyi/autocomplete-python#189]
Hello I'm very new to coding so maybe this is something on my side. I was wondering if the tkinter functions are part of the plug-in until now it does not autocomplete any requested function (for instance : canvas.create_line)  Otherwise it works pretty smooth.

Thank you

**Comment by sadovnychyi** [comment]
I cannot help you if other installed packages works well for you. If tkinter is not pure python library then it will not work.
