### ISSUE TITLE
Support for minimal word length

### ISSUE THREAD

**Issue by zenwalker** [sadovnychyi/autocomplete-python#191]
For sample autocomplete-plus has the same option.
![2016-03-17 15-57-49 settings users maxim projects simply simply-backend](https://cloud.githubusercontent.com/assets/1812128/13846559/0de436fa-ec59-11e5-96d0-2bc085c2aa2e.png)

**Comment by sadovnychyi** [comment]
You could edit `triggerCompletionRegex` option to something like `([\.\ ]|[a-zA-Z_][a-zA-Z0-9_]{3,})` instead of `([\.\ ]|[a-zA-Z_][a-zA-Z0-9_]*)` by default.

**Comment by zenwalker** [comment]
Oh, Thanks! Forgive me for inattention.
