### ISSUE TITLE
"EOF in backquote substitution" throw every time I type while looking for bin/python in the wrong folder

### ISSUE THREAD

**Issue by web-snake** [sadovnychyi/autocomplete-python#192]
After the last update it seems to throw errors every time or almost every time I type anything in my python files. The message is : "EOF in backquote substitution".
But the error message also logs another apparent problem that may be causing the error:
It tells me 3 times that its unable to find the bin/python, which is expected since its looking in the wrong place. Its looking under another project folder and a subfolder off that named by a virtual env that I'm not using for this project. Even if I where using that project, the virtual env that contains python/bin is located in the standard location :  /home/{user}/.virtualenvs/{virtualenv} and not under any project folder.
I am using the Atom virtualenv extension and it has an option to change virtualenvs that I thought might clear up autocomplete-pythons confusion about what virtualenv to look for and the location that its would be at. But it doesn't after deactivating all virtualenv's its still looking the same folder for bin/python and when I activate the virtualenv I'm using for the current project, it does the same thing:
looks in the project folder for the wrong project for the wrong virtual env.

**Comment by sadovnychyi** [comment]
Can you give me your python executable config from package settings? Also, please, enable debug logs and look there for something like this:

![image](https://cloud.githubusercontent.com/assets/193864/13897078/6dfebfca-edde-11e5-80c4-7b8f371c7d38.png)

**Comment by web-snake** [comment]
Looks like it was a problem with the python executable path that was created by using the project on multiple computers. Setting those settings did the trick.
Thanks
