### ISSUE TITLE
Doesn't show methods of base class

### ISSUE THREAD

**Issue by orodbhen** [sadovnychyi/autocomplete-python#193]
I'm only seeing completion suggestions for direct class methods, but it doesn't show methods for the base class. There's a menu in the settings that may relate to this, but it's unclear what it's for. It has options `None`, `All`, and `Required`.

**Comment by sadovnychyi** [comment]
![image](https://cloud.githubusercontent.com/assets/193864/13896617/4e10f0d6-edcd-11e5-97ba-825983ebdcbb.png)

That setting is related to argument completion, nothing to do about methods.

**Comment by orodbhen** [comment]
So is there a setting that causes deeper attribute resolution for classes?

**Comment by sadovnychyi** [comment]
No, everything should work out of the box. Unless there are some errors from Jedi.

**Comment by Mohanson** [comment]
I'm looking forward to seeing this feature because I got disturbed by base method sometimes. I want hidden this myself but I'm really not good at js.

**Comment by sadovnychyi** [comment]
@Mohanson can you explain please? Do you want an option to **hide** base methods?
This issue is about methods not being shown.

**Comment by Mohanson** [comment]
@sadovnychyi , I am sorry that I didn't take a close look at this issue. Which I want to hide is **Magic method** just like "__name__" or "__doc__", not **Methods of base**.

**Comment by sadovnychyi** [comment]
But it's seems like methods starting with underscores are always ranked lowest, thus why would you want to hide them?
![image](https://cloud.githubusercontent.com/assets/193864/14074879/e975daec-f506-11e5-9642-68b8a91beff7.png)

**Comment by Mohanson** [comment]
I almost never going to use them, but I have to see them again and again...in any object.

**Comment by sadovnychyi** [comment]
There's always a lot of noise in autocomplete, I'm not sure how is it possible to hide something. Just type what you want to filter them out.
