### ISSUE TITLE
Go To Definition throws error

### ISSUE THREAD

**Issue by Taygrim** [sadovnychyi/autocomplete-python#194]
When I try to go to the definition of defaultdict in the next line
`from collections import defaultdict`
I get an error:

> Traceback (most recent call last):
>   File "/Users/Taygrim/.atom/packages/autocomplete-python/lib/completion.py", line 339, in watch
>     self._process_request(self._input.readline())
>   File "/Users/Taygrim/.atom/packages/autocomplete-python/lib/completion.py", line 316, in _process_request
>     script.goto_assignments(), request['id']))
>   File "/Users/Taygrim/.atom/packages/autocomplete-python/lib/completion.py", line 249, in _serialize_definitions
>     'line': definition.line - 1,
> TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
>

**Comment by sadovnychyi** [comment]
Fixed it to not throw an error, but you still cannot go to definition from defaultdict since it's not written on pure python.
