### ISSUE TITLE
Anaconda, multiple site-packages without manual copy and paste.

### ISSUE THREAD

**Issue by mburke05** [sadovnychyi/autocomplete-python#197]
Hi guys,

I came across this when looking for something similar to the responsiveness of bpython in an IDE. I'm sort of getting the hang of it. I was wondering if there was a way to import all or groups of site-packages rather than having to manually copy and paste each libs path. I'm not editing in a virtual environment so I might be misunderstanding the use of the site-packages custom paths here. 

Thanks,
Matt

**Comment by sadovnychyi** [comment]
Simply set path to python executable you want to use, it should use site-packages from there.
