### ISSUE TITLE
Updating autocomplete-python always results in an error

### ISSUE THREAD

**Issue by Enkouyami** [sadovnychyi/autocomplete-python#20]
Ever since atom v0.200 updating this packages always has this error: `exit with code null, signal SIGTERM`. Before v0.200 it still happened, but not every update for it.

**Comment by sadovnychyi** [comment]
But is it works properly after restarting the atom?

**Comment by sadovnychyi** [comment]
This is will be fixed with next release, note that you will get this error one more last time while updating on new release.

**Comment by Enkouyami** [comment]
Yeah it still works after restarting atom and thanks for the update.
