### ISSUE TITLE
autocomplete-python unable to find python binary.

### ISSUE THREAD

**Issue by agunpratama** [sadovnychyi/autocomplete-python#200]
This is the first time I try to code with python using atom. Then I came acrross your package, I've installed it, but it couldn't work and keep making notification such as autocomplete-python unable to find python binary. I've installed Python 2.7.1 on my Windows 7 in directory (C:\Python27), and I have had put this in "python executable paths" but it doesn't work. I've checked in (C:\Users\) but there isn't any python folder neither in any folder in my windows, there's just one folder (C:\Python27) that contain my python. Can you help sort this out?

**Comment by sadovnychyi** [comment]
Did you set a full path to python executable like `C:\Python27\python.exe`?

**Comment by agunpratama** [comment]
Hahaha, thank you for your help, I finally figure it out. Thank you so much :).

**Comment by shhivam** [comment]
How to set path for python executable binary file?

**Comment by sadovnychyi** [comment]
From package settings.

**Comment by shhivam** [comment]
Can u elaborate?

**Comment by sadovnychyi** [comment]
@shhivam 

![image](https://user-images.githubusercontent.com/193864/34069316-bfcb1a32-e289-11e7-9047-7d6f52da1196.png)

**Comment by shhivam** [comment]
@sadovnychyi  Sorry to bother you, friend but how do i know the path of the python executable. 
I know it is a silly question but i am new in the boat, could you please tell me?

**Comment by sadovnychyi** [comment]
Output of "which python" in your terminal would work.

**Comment by shhivam** [comment]
@sadovnychyi I tried to run "which python" on my windows CMD but got an error saying " which is not recognised as an internal or external command, operable program or batch file".   What do i do?

**Comment by sadovnychyi** [comment]
Yeah, that works only in bash-like environments.

On windows it could be in your program files (if installed globally) or in `%LocalAppData%` folder (e.g. `C:\Users\You\AppData\Python\python.exe`). You can just re-install it again to see exact location. Note that it should point exactly on `python.exe` file.

**Comment by shhivam** [comment]
Thank you so much ! 
You really are genius !

**Comment by slaugea** [comment]
I've got the same issue however when i use my path:  C:\Python27\python.exe 
Nothing changes for autocomplete-python for me.  My Python is not in "program files" or Program Files (x86)"  So i'm not sure if I have two problems vs this one.  Any help would be greatly appreciated.

I was getting the following error until i changed the path to "C:\Python27\python.exe" and now I'm at least not getting the error, just autocomplete is not functioning at all.

autocomplete-python unable to find python binary.
Please set path to python executable manually in package
settings and restart your editor. Be sure to migrate on new settings
if everything worked on previous version.
Detailed error message: 'C:\Python27\' is not recognized as an internal or external command,
operable program or batch file.
Current config: C:\Python27\

**Comment by Help-Me-Please1103** [comment]
So do  we have to download Python seperately.

**Comment by DavidCohen90** [comment]
Hi!
I'm using Atom on Windows 10 alongside with an Ubuntu environment, natively available now with Windows 10 (ie without any dualboot or virtual machine). I thought about using the Python library available on Ubuntu (like usually /usr/bin) but it seems not working. The Ubuntu folders/files are actually readable/writable/executable from the Windows explorer.
I don't know whether this is clear enough. If it is, is there a way to make it work? Or in the near future? Else I'd install the Python library on Windows.
Thanks!

**Comment by sachchauhan07** [comment]
hi
i have set the python path and it is also not showing any error but the autocomplete is still not working please help
