### ISSUE TITLE
Add delay to showing list of autocompletions

### ISSUE THREAD

**Issue by vmrob** [sadovnychyi/autocomplete-python#201]
I installed this plugin, thought it was great, and then quickly became very irritated about how _good_ it is at determining autocompletions. It's too good--too fast. Simply put, I think there should be a setting to determine an amount of time between keystrokes that must occur before it begins to suggest autocompletions.

As is, the plugin is _so good_ at getting autocompletions that it is distracting while writing code. I think the behavior should wait for a X milliseconds to have elapsed before providing suggestions. Once it has provided those suggestions, it should continue to do so just as it does now with no delay. However, once its hits a word boundary, the delay should be reset.

**Comment by sadovnychyi** [comment]
Have you seen this autocomplete-plus setting?
![image](https://cloud.githubusercontent.com/assets/193864/14518849/695e7a22-024d-11e6-9e53-0dd5b7932be3.png)

Should work for you. Will affect other autocomplete providers as well.

**Comment by vmrob** [comment]
Perfect! I had not seen that. Thank you.
