### ISSUE TITLE
[Question] Is there a way to return-from-definition

### ISSUE THREAD

**Issue by amoghe** [sadovnychyi/autocomplete-python#203]
Ctrl-Alt-G can take me to a symbol, but is there a way to go back to where I came from, so that I can continue investigating the original code flow?

**Comment by sadovnychyi** [comment]
No, currently there's no such feature. This mostly depends on an API for symbols package. There's unfinished pull request for this.

**Comment by sadovnychyi** [comment]
https://github.com/atom/symbols-view/issues/70
https://github.com/atom/symbols-view/pull/95
