### ISSUE TITLE
Atom doesn't show default functions 

### ISSUE THREAD

**Issue by daurenm** [sadovnychyi/autocomplete-python#211]
On my laptop, the plugin doesn't suggest any default functions (like "choice_set", "order_by" e.g.) for objects. But default python shell does. 

Debian 8.4. Atom's init script : 
process.env.PATH = ['/usr/local/bin/', '/home/red/.linuxbrew/bin', process.env.PATH].join(':')

**Comment by sadovnychyi** [comment]
I cannot remember any built ins with such name. Does other completions work for you?

**Comment by daurenm** [comment]
Yes. Right now I'm working with Django project. Probably those functions
are default Django functions. Is there any way to add them?
Thanks for your response.

On 7 June 2016 at 17:52, Dmytro Sadovnychyi <notifications@github.com>
wrote:

> I cannot remember any built ins with such name. Does other completions
> work for you?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sadovnychyi/autocomplete-python/issues/211#issuecomment-224257636>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMwshH5UIXAvNeN6sCPje5t2wP55NnRmks5qJVtggaJpZM4Iv1Dy>
> .
>



-- 
Best Regards !
Dauren Muratov

**Comment by sadovnychyi** [comment]
Try to add path to your django lib in extra paths. Look on package settings – it has a lot of them.

**Comment by daurenm** [comment]
Well, I added these
[/home/red/.linuxbrew/Cellar/python/2.7.11/lib/python2.7/site-packages/django]
to "extra paths for packages". But it still doesn't work :(.
Functions, which on auto complete should work are inside Django's Query
API.

On 7 June 2016 at 18:25, Dmytro Sadovnychyi <notifications@github.com>
wrote:

> Try to add path to your django lib in extra paths. Look on package
> settings – it has a lot of them.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sadovnychyi/autocomplete-python/issues/211#issuecomment-224264503>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMwshMeGdwUZZuupnqoKnLV9zXIhtjkMks5qJWNLgaJpZM4Iv1Dy>
> .
>



-- 
Best Regards !
Dauren Muratov

**Comment by sadovnychyi** [comment]
I'm not 100% sure that Jedi is capable to complete functions you are talking about. Does simple `import dja` works for you to get completions for module name?

Try to put simple `/home/red/.linuxbrew/Cellar/python/2.7.11/lib/python2.7/site-packages` in extra paths.
