### ISSUE TITLE
It couldn't list all functions when I use the dot symbol.

### ISSUE THREAD

**Issue by yanyuzhy** [sadovnychyi/autocomplete-python#214]
`import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

plt.`

I want to list all functions and classes of matplotlib.pyplot using dot , but it was failed in
Autocomplete-python , While I can do it in pycharm.

why ?

Could anyone help me? thanks a lot.

**Comment by sadovnychyi** [comment]
It's jedi related issue, please track it here:
https://github.com/davidhalter/jedi/issues/730

I'll make sure to update autocomplete-python once it's fixed there.

**Comment by yanyuzhy** [comment]
OK, thank you very much!

**Comment by sadovnychyi** [comment]
Tensorflow should work in latest version, thanks to updates in Jedi.

![image](https://cloud.githubusercontent.com/assets/193864/16800791/abc47182-4929-11e6-916f-336da912d9d4.png)

In python3 you may need to manually re-install `six` package. Track original Jedi bug for more info.

**Comment by drorata** [comment]
I have a similar problem with all packages. The autocompletion doesn't detect them. I'll be happy to provide feedback.
