### ISSUE TITLE
cannot use this plug-in

### ISSUE THREAD

**Issue by Vermouth1995** [sadovnychyi/autocomplete-python#215]
when I am coding,it will show like this:
autocomplete-python traceback output:
'python' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

**Comment by sadovnychyi** [comment]
What system local do you use? Are you sure that you configured the plugin properly and python executable is available?

**Comment by Vermouth1995** [comment]
I‘m using Python3.5,and I have just installed the plugin that used the default configuration~when I am entering such as 'import',it will show like that~

**Comment by Vermouth1995** [comment]
Oh I‘m so sorry~There is some problems with my configuration.Now I can use it very well.Thank you very much and your plugin is very convenient~
