### ISSUE TITLE
Can't make it work with my own modules

### ISSUE THREAD

**Issue by giordan12** [sadovnychyi/autocomplete-python#216]
This might be some configuration issue but does this package recognize modules inside a project? I cannot get it to autocomplete methods from a class that is imported from another file.

**Comment by sadovnychyi** [comment]
It should. It depends on your project hierarchy, extra paths and/or executables settings. Usually it works out of the box though.

**Comment by giordan12** [comment]
I think it's an issue with the project hierarchy, I have:
/Project1
    /Test:
    ----->__init__.py
    ----->test1.py (File that imports the class)
   / Help:
    ----->__init__.py
    ----->assistance.py(File that contains the class)
On test1.py I attempt to import using "from Help.assistance...", but it does not recognize them as packages for some reason. Am i doing anything wrong here?

**Comment by sadovnychyi** [comment]
Try to add `__init__.py` on the top level, next to /Project1, /Test and /Help folders. When you open your Atom project you can see all these folders in side panel right?

**Comment by giordan12** [comment]
That fixed it after closing and reopening Atom, I love this package it's so useful. Thanks for the help!
