### ISSUE TITLE
Auto-complete not working for virtual environment

### ISSUE THREAD

**Issue by JamesStidard** [sadovnychyi/autocomplete-python#217]
I've managed to get the package working while leaving the paths empty in the package config for non virtualenviroments. However, it does not work with my actual projects that use virtual environments.

Is there a way I can go about debugging this? I've been fiddling around with it for a couple evenings trying to figure out the issue.

Here are the settings I'm trying to use:
<img width="683" alt="screen shot 2016-07-25 at 10 51 07 pm" src="https://cloud.githubusercontent.com/assets/1797906/17118896/d212a7ce-52ba-11e6-93a5-c98607fb9bb2.png">

My project directories looks like:
- Project
 - example
 - tests
 - venv

I've turned on the debugging to console and all the paths look correct. I use `$ virtualenv -p python3 venv` in the project directory to create my virtual environments. I've tried both opening the project in Atom normally as well as activating the environment in terminal `$ source venv/bin/activate` then `atom .`.

I do see this though when I turn on debugging (was typing `import tornado.` as the time):
```
autocomplete-python: autocomplete-python traceback output: Traceback (most recent call last):
  File "/Users/jamesstidard/.atom/packages/autocomplete-python/lib/jedi/parser/utils.py", line 67, in load_parser
    parser_cache_item = parser_cache[path]
KeyError: '/Users/jamesstidard/Development/Project/venv/lib/python3.5/site-packages/tornado/__init__.py'

During handling of the above exception, another exception occurred:

... (large stack trace - can post if relevant)
File "/Users/jamesstidard/.atom/packages/autocomplete-python/lib/jedi/parser/utils.py", line 129, in load_parser
    parser_cache_item = pickle.load(f)
AttributeError: Can't get attribute 'Whitespace' on <module 'jedi.parser.tree' from '/Users/jamesstidard/.atom/packages/autocomplete-python/lib/jedi/parser/tree.py'>
```
Thanks.

**Comment by leonelfreire** [comment]
Hello,

Same problem here. I decided to investigate and it seems that this is a problem with Jedi (there's a new version in autocomplete-python 1.8.4).

One class from the package `jedi/parser/tree.py` was renamed from Whitespace to Newline:
![screenshot_2016-07-26_00-25-54](https://cloud.githubusercontent.com/assets/14333/17125298/a3c89852-52c8-11e6-862a-f0036d474bf3.png)

This was affecting the pickle cache generated by Jedi (it was pointing to the old class):
![screenshot_2016-07-26_00-22-27](https://cloud.githubusercontent.com/assets/14333/17125531/9dd216f6-52ca-11e6-8f3a-8f411505aa1e.png)

Removing the folder `~/.cache/jedi` solved the problem. I don't know where this folder is located in Windows. Sorry. :-(

**Comment by pchomik** [comment]
Solution provided by @leonelfreire solves problem for me (Debian Jessie).

**Comment by sadovnychyi** [comment]
Reported an issue for Jedi.

Cache locations:
> On Linux, this defaults to ~/.cache/jedi/, on OS X to ~/Library/Caches/Jedi/ and on Windows to %APPDATA%\Jedi\Jedi\. On Linux, if environment variable $XDG_CACHE_HOME is set, $XDG_CACHE_HOME/jedi is used instead of the default one.

**Comment by JamesStidard** [comment]
This was the indeed the issue; everything seems to be working after deleting that jedi cache folder.

Thanks everyone.
