### ISSUE TITLE
AttributeError in latest version

### ISSUE THREAD

**Issue by muppetjones** [sadovnychyi/autocomplete-python#218]
```python
File "/usr/local/var/pyenv/versions/2.7.11/lib/python2.7/pickle.py", line 1096, in load_global
    klass = self.find_class(module, name)
  File "/usr/local/var/pyenv/versions/2.7.11/lib/python2.7/pickle.py", line 1132, in find_class
    klass = getattr(mod, name)
AttributeError: 'module' object has no attribute 'Whitespace'
```

This happens when typing, regardless of what I have set for the python executable paths or extra paths for packages.

**Comment by sadovnychyi** [comment]
Remove your cache.

> On Linux, this defaults to ~/.cache/jedi/, on OS X to ~/Library/Caches/Jedi/ and on Windows to %APPDATA%\Jedi\Jedi. On Linux, if environment variable $XDG_CACHE_HOME is set, $XDG_CACHE_HOME/jedi is used instead of the default one.

See https://github.com/sadovnychyi/autocomplete-python/issues/217.
