### ISSUE TITLE
Errors after update whenever typing anything inside parenthesis

### ISSUE THREAD

**Issue by BrunoBernardino** [sadovnychyi/autocomplete-python#223]
So I'm getting an `AttributeError: 'module' object has no attribute 'Whitespace'` since a couple of days ago whenever typing anything (not always, but 80% of times).

I haven't been able to find a pattern for why. I can see it happening for just typing new variables, variables inside parenthesis, etc. Basically anywhere.

<img width="449" alt="screen shot 2016-08-05 at 15 02 16" src="https://cloud.githubusercontent.com/assets/1239616/17451700/a9106328-5b1d-11e6-9f21-20e12968dbb8.png">

I'm on 1.8.5 (was happening on 1.8.4).

Atom 1.9.5

**Comment by sadovnychyi** [comment]
See #219.

**Comment by BrunoBernardino** [comment]
Thanks, it's working!
