### ISSUE TITLE
it doesn't work with atom 1.9.8

### ISSUE THREAD

**Issue by n3ph7hy5** [sadovnychyi/autocomplete-python#225]
I updated atom and it just doesn't work at all

**Comment by sadovnychyi** [comment]
Please provide more details. Any exceptions? Logs?

**Comment by n3ph7hy5** [comment]
sorry, it actually works if I don't split the editor. 
e.g. if I split right it works on the left but not in the right side.
       sometimes (if I have the same file on left and right) I write in right and it appears on the left (but not always)

**Comment by sadovnychyi** [comment]
Enable logs in package settings and you can find them in Dev Tools.

But I'm more curious if other completions works for you (like built in or snippets)?

**Comment by n3ph7hy5** [comment]
uhm...english please? xD
Anyway, new update, It works properly when I open single files(and split).
It doesn't work when I open folders(and split)!

**Comment by n3ph7hy5** [comment]
sorry for bothering you, it doesn't work even with the other completions! My fault!
