### ISSUE TITLE
Sorry,i can't use this plugin.

### ISSUE THREAD

**Issue by DimmuSun** [sadovnychyi/autocomplete-python#229]
Sorry,i can't use this plugin. I use Windows 7 and i think my plugin settings is wrong,how can i correct it.

**Comment by DimmuSun** [comment]
![image](https://cloud.githubusercontent.com/assets/21170420/17849319/db57e624-688a-11e6-8bab-a0fce473b750.png)

**Comment by DimmuSun** [comment]
![image](https://cloud.githubusercontent.com/assets/21170420/17849373/0d8a5b18-688b-11e6-99f9-508e6ccf395c.png)

**Comment by sadovnychyi** [comment]
Python executable paths for windows should end with .exe AFAIK.
Something like `C:\Users\lenovo\AppData\Local\Programs\Python\Python36\python.exe` for your case. Make sure you can launch python at this path using `Ctrl + R` or something.
