### ISSUE TITLE
Error while updating: exit with code null, signal SIGTERM

### ISSUE THREAD

**Issue by RickDavis84** [sadovnychyi/autocomplete-python#24]
on both windows & ubuntu immediately after clicking update for the autocomplete-python v 0.5.0 throws an error just saying "exit with code null, signal SIGTERM". The update appears to complete successfully though.

**Comment by sadovnychyi** [comment]
As I have mentioned in #20 -- this is should be the last time you saw this error. Future update shouldn't spawn it.

Duplicate of #18 #20 #23 :open_mouth:
