### ISSUE TITLE
Python 3 binary lookup, add bracket and dot configurations

### ISSUE THREAD

**Issue by mdalpi** [sadovnychyi/autocomplete-python#26]
Hi. I'm not an expert, but you looking only for python binary (in all the PATH directories) and not python3? For example, in my /usr/local/Cellar/python3/3.4.3/bin I only have python3 and python3.4 binaries. Of course I can make a symbolic link, but it wouldn't be better to specify the binary directly?

Also, I can't make work the options do add a bracket after function and dot after module.
Lastly, there's a way to hide the descriptions of a functions?

Thanks

- [x] Parameter to hide doc strings
- [ ] Fix bracket after function param
- [ ] Fix dot after import param
- [x] Lookup for both python and python3 executables

**Comment by sadovnychyi** [comment]
Hey, I thought that `python3` is always symlinked with `python`, but if this is not true -- then we definitely should look for `python3` as well. I will take a look about how to implement it.

I'm passing the brackets option directly to JEDI, as described here:
http://jedi.jedidjah.ch/en/latest/docs/settings.html#jedi.settings.add_bracket_after_function
I can confirm that it does not work. Will take a look.

I can add an extra option to plugin settings to hide the descriptions, will that be enough?

**Comment by sadovnychyi** [comment]
Added option to hide the doc strings. Note that in future once autocomplete-plus will support HTML in descriptions -- they should look much better.

Looks like JEDI's add bracket after function is does not works, and I cannot fix it.
Have you tried to use "Complete with snippets" option?

**Comment by mdalpi** [comment]
And thanks for the option to hide doc string :grin:

**Comment by mdalpi** [comment]
A quick dirty fix for the Jedi's "add bracket and dot" will be something like this:
![](https://cloud.githubusercontent.com/assets/6289699/8379086/ebdc3796-1bf3-11e5-8cc6-c8c7ff438a09.png)
But the cursor is not in the middle of the brackets in case of the function, and the suggestions are not being displayed after the dot for modules (like if you have actually typed the dot).

**Comment by sadovnychyi** [comment]
I'll test your pull request tomorrow. To put a cursor inside of brackets we have to use snippets. And its not so easy with dot after import since it should be appended only in certain cases.

**Comment by sadovnychyi** [comment]
So, if you still want to include only brackets, why not to extend your pull request changes with "brackets only" option? Seems easy to do.

Is there are any cases when we are 100% sure that we need to append a dot after import?
`from datetime import datetime` -- no
`import datetime.datetime` -- no

**Comment by isolet** [comment]
I'm wondering how to specify the binary directly too.
