### ISSUE TITLE
autocomplete-python doesn't seem to make use of PYTHONPATH

### ISSUE THREAD

**Issue by warbands** [sadovnychyi/autocomplete-python#29]
autocomplete-python doesn't seem to make use of PYTHONPATH

I am trying to use this package under Windows, and my PYTHONPATH environment variable which works in the cmd shell ( I am able to launch Python with no issue ) yet when I launch Atom from this very same shell, the autocomplete-python package is unable to locate the python executable. I even tried to set the "Path to Python Directory" to %PYTHONPATH% ( and even tried the unix style $PYTHONPATH ) yet I am still unable to find the python executable according to your package. I also verified that our python directory is also in our PATH as well, yet seemingly ignored. 
Due to how complex our environment setup is, I can't simply drop in a C:\whatever directory into this field, I need to rely on our environment settings.

If you have any thoughts, let me know, thanks in advance.

**Comment by sadovnychyi** [comment]
Sorry for late response.
I'm not sure that you can use environment variables inside of those settings. Are you looking for python executable somewhere inside of your project? Have you tried the $PROJECT variable?

**Comment by jan4843** [comment]
My modules in `/usr/local/lib/python2.7/site-packages`, for example, doesn't get loaded. I also tried adding the path to the `Extra PATH` setting but it still doesn't work.

My PYTHONPATH:
```python
>>> import sys
>>> sys.path
['', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages/PyObjC', '/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg', '/Library/Python/2.7/site-packages']
```

An example: I have the `rumps` module installed via `pip`
```
$ ls /usr/local/lib/python2.7/site-packages/rumps
__init__.py  packages/    rumps.py     utils.py
```
but I don't see it in autocompletion
![screenshot](https://cloud.githubusercontent.com/assets/1881325/8640082/f36c271e-28eb-11e5-8379-f6309d0e915e.png)

**Comment by sadovnychyi** [comment]
Closing this in favor of #66.
