### ISSUE TITLE
Autocomplete function arguments

### ISSUE THREAD

**Issue by blapid** [sadovnychyi/autocomplete-python#31]
Hi,

I'm not sure if it's by-design,  a problem with my setup or a general issue, but I can't get it to autocomplete/suggest function arguments.
For reference, in my opinion "bpython" has some pretty neat autocompletion for function arguments. I'd love to see something like that added here, if possible.

In any case, thanks for the work on this package :)

**Comment by sadovnychyi** [comment]
It works just well for me, but note that this feature is disabled by default, you have to turn it on in package settings:
![image](https://cloud.githubusercontent.com/assets/193864/10273778/3dcb04d8-6b68-11e5-910d-09dc28a84a03.png)

![sample](https://cloud.githubusercontent.com/assets/193864/10273791/8126f44e-6b68-11e5-9dab-cb76ad0559b8.gif)
