### ISSUE TITLE
Attempt to Reload if Python Process is Terminated

### ISSUE THREAD

**Issue by michaelhelmick** [sadovnychyi/autocomplete-python#32]
If python crashes or the kill signal is sent to python, Atom reports:

`autocomplete-python provider exit`
`exit with code null, signal SIGKILL`

Would it be possible to attempt to reload the plugin or is this an Atom issue?

**Comment by sadovnychyi** [comment]
Yeah it's possible, I'll take a look later.

**Comment by michaelhelmick** [comment]
Thank you!

**Comment by michaelhelmick** [comment]
:cake:
