### ISSUE TITLE
How to shorten the delay?

### ISSUE THREAD

**Issue by zomux** [sadovnychyi/autocomplete-python#33]

**Comment by sadovnychyi** [comment]
Delay of autocompletions? It could be long for the first time while your project is being cached, and should be fast after. Can you give me more info?

**Comment by zomux** [comment]
Well, actually it's not slow, delays for 1 ~ 2 second now, 

but I want more, say, 200ms just like sublime text

**Comment by sadovnychyi** [comment]
Is it works fast for other autocomplete providers? For me the delay is less than 100ms and I'm not sure how to help you.
