### ISSUE TITLE
CPU drain even after atom has exited

### ISSUE THREAD

**Issue by dessant** [sadovnychyi/autocomplete-python#37]
I have closed atom a hour ago and no atom processes are running, but a python one is still alive and busy.

![screenshot from 2015-07-18 14-33-34](https://cloud.githubusercontent.com/assets/7513068/8761428/116f651a-2d5a-11e5-8619-ad70e98b6365.png)

**Comment by dessant** [comment]
A kivy process picked up the exception, this traceback was being repeated, producing a 6 GB log file.

```python
[WARNING           ] stderr: Traceback (most recent call last):
[WARNING           ] stderr:   File "/home/vix/.atom/packages/autocomplete-python/lib/completion.py", line 169, in watch
[WARNING           ] stderr:     self._process_request(sys.stdin.readline())
[WARNING           ] stderr:   File "/home/vix/.atom/packages/autocomplete-python/lib/completion.py", line 143, in _process_request
[WARNING           ] stderr:     request = self._deserialize(request)
[WARNING           ] stderr:   File "/home/vix/.atom/packages/autocomplete-python/lib/completion.py", line 116, in _deserialize
[WARNING           ] stderr:     return json.loads(request)
[WARNING           ] stderr:   File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
[WARNING           ] stderr:     return _default_decoder.decode(s)
[WARNING           ] stderr:   File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
[WARNING           ] stderr:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[WARNING           ] stderr:   File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
[WARNING           ] stderr:     raise ValueError(errmsg("Expecting value", s, err.value)) from None
[WARNING           ] stderr: ValueError: Expecting value: line 1 column 1 (char 0)
```

**Comment by sadovnychyi** [comment]
Cannot reproduce it, it closes the child process after you quit Atom our deactivate the package. And this is, actually, done by https://github.com/atom/autocomplete-plus API:
https://github.com/sadovnychyi/autocomplete-python/blob/master/lib/provider.coffee#L124-L126

**Comment by dessant** [comment]
I suspect the process was not closed because the exception was rised again and again, keeping the process busy, unless atom sends a sigkill, but I doubt that.

I don't know how to give you more information, I have this stack trace only and I have not seen the issue since then.

**Comment by sadovnychyi** [comment]
Unfortunately if something went wrong with Atom and it didn't call the dispose method there are no way to kill it programmatically.

https://github.com/sadovnychyi/autocomplete-python/blob/master/lib/provider.coffee#L155-L157

Maybe in future we could check from the python side if there are still Atom process running, and make a suicide if its not found.

**Comment by patrys** [comment]
Maybe it would be possible to detect when the `sys.stdin` stream is closed?

**Comment by sadovnychyi** [comment]
@patrys really don't know how to do it from python side and it does not make sense to do from Atom's side. I just tried to `kill`/`kill -9` atom and it's always terminates Python process as well. Maybe it something got fixed in latest Atom/autocomplete-plus releases.

**Comment by dessant** [comment]
The odd thing was that the python process used by autocomplete-python somehow shared state with the process started by atom-script so the autocomplete-python exception got picked up by my app instance. I don't understand why did this happen, I would expect these processes to be completely independent.

**Comment by sadovnychyi** [comment]
cc @rgbkrk, @erran maybe they have some ideas.

**Comment by rgbkrk** [comment]
Wow that's insane. 6GB of logs.

**Comment by sadovnychyi** [comment]
@rgbkrk question is that possible that atom-script got control over child process of autocomplete-python?

**Comment by rgbkrk** [comment]
Are you using `BufferedProcess` from Atom?

**Comment by sadovnychyi** [comment]
No, raw node's child process: https://github.com/sadovnychyi/autocomplete-python/blob/master/lib/provider.coffee#L46

**Comment by rgbkrk** [comment]
I'd need more logs for me to see process hijacking as even remotely possible.
