### ISSUE TITLE
Join Forces?

### ISSUE THREAD

**Issue by tinloaf** [sadovnychyi/autocomplete-python#4]
Hi Sadovnychi,

while I neither can nor want to stop you from producing software, developing yet another acp-python provider feels like a waste of your time as well as mine. ;) I hope you did not feel as if I would not welcome your contributions because I did not yet merge https://github.com/tinloaf/autocomplete-plus-python-jedi/pull/15 - this had multiple reasons. Amongst them:

* I was aiming at a little broader solution (see below)
* There were multiple commits targeting different problems in that PR

I did now create this branch: https://github.com/tinloaf/autocomplete-plus-python-jedi/tree/pythonpaths - as you can see, this more or less incorporates your proposed changes, but will take a 'multiple processes' approach: For every editor window, a list of paths to be added to the PYTHONPATH is determined, and if no jedi process for that combination of paths exists yet, one is spawned. That way, it's possible to have multiple files in different virtualenvs open, etc.

Now, to cut a long story short: Interested in working together? I'd even abandon my beloved tabs for PEP8-compliant spaces... ;)

**Comment by sadovnychyi** [comment]
Join forces -- sounds good for me, as well as spaces instead of tabs in python :+1: 
But I've created this package just to move faster and be able to use it by myself **right now**.

When I've installed your package for the first time I was really exited about Jedi, but then I saw that it not even able to see "sibling" modules from the same folder I'm currently editing. So I started editing your package, made a pull request, it took long time, I saw that you have broken build and no specs -- so I've created Yet Another Python Autocomplete. :)

Feel free to merge any code from here.

**Comment by tinloaf** [comment]
Great. I'll merge the pythonpaths-branch later today - could you then give that another try, i.e. see if it will find the 'sibling' modules you were interested in?

**Comment by tinloaf** [comment]
Just released 0.3.0 of acp-python-jedi which should find modules 'next to' what you're currently editing. Could you try if your use case is covered by this?

**Comment by aioue** [comment]
any update on the package merge?

**Comment by ergo** [comment]
bump.

**Comment by sadovnychyi** [comment]
How this merge should happen? The original repository has a lot of unsolved issues and its still unusable for me personally as I have applied a lot tweaks here.

**Comment by tinloaf** [comment]
Yep. Looking at this, it makes a lot more sense to just make all people switch to using your plugin. Too little time on my side, sorry. Now, I don't think the Atom devs have lined out any way of merging two plugins, have they? 
cc @benogle

**Comment by benogle** [comment]
@tinloaf I can 'deprecate'  tinloaf/autocomplete-plus-python-jedi and recommend this package instead. Would that be sufficient?

**Comment by tinloaf** [comment]
My solution would have been to open a pop-up when the plugin is loaded and tell people to switch over to the other plugin. But if you have a way of doing this "right", please go ahead, @benogle!

**Comment by benogle** [comment]
Popups are scary. I'd rather just have it show up in the updates screen. When you guys are ready, I can deprecate one package for the other.

**Comment by tinloaf** [comment]
From my side: Go ahead. I've switched myself and consider my code abandoned now...

**Comment by bilderbuchi** [comment]
@benogle time to deprectate @tinloaf's package?

**Comment by tinloaf** [comment]
Please do! Judging from the issues in my old repo, people are still using it...

**Comment by benogle** [comment]
`autocomplete-plus-python-jedi` has finally been deprecated in atom/master and will point to this repo on the next release

**Comment by bilderbuchi** [comment]
thanks!
