### ISSUE TITLE
Goto commands support

### ISSUE THREAD

**Issue by asaitgalin** [sadovnychyi/autocomplete-python#43]
Hello!

In jedi-vim or SublimeJEDI there is an options to specify hotkeys for "goto assignment" and "goto definition" commands. Do you plan to add this to your package? I have not found this feature. 

Thanks in advance!

**Comment by ferdy-galema** [comment]
For what it's worth: This is currently possible with the atom-ctags ( https://atom.io/packages/atom-ctags ) package. Although it has more language support than just python, so what I do is simply exclude all other file types to prevent the symbol building from exploding. Also this allows for global symbol browsing.

You may want to use it for inspiration when building the support in this package.

**Comment by patrys** [comment]
See #68
