### ISSUE TITLE
Installing From Atom for Mac Preferences Errors : exit with code 1, signal null

### ISSUE THREAD

**Issue by A-M-R** [sadovnychyi/autocomplete-python#45]
I tried to install autocomplete-python within Atom1.0.2 for Mac>Preferences>Install and I immediately got a big red error box in the upper right hand corner. I tried to quit and restart Atom a few times, but each time Atom opens, the error pops up.
<img width="733" alt="screen shot 2015-07-26 at 5 04 05 pm" src="https://cloud.githubusercontent.com/assets/13447051/8895903/773f1e6c-33b8-11e5-85d9-371d681a5fd2.png">

**Comment by sadovnychyi** [comment]
Can you give me an output of `which python` please?
And is there are anything in dev console (open it by pressing `Option + CMD + I`)?

**Comment by A-M-R** [comment]
Okay, information requested below, however there is a new piece of information to give you. When I start Atom from the Mac Application icon I get the error. When I start Atom from the Command Line in Terminal, there is no error, and the autocomplete seems to work fine. :interrobang:

`which atom` yields `/usr/local/bin/atom`.

The shell script seems to just call Applications/Atom.app, so I have no idea why there are different results.

I disabled `autocomplete-python` and there is no python autocomplete, so when run with CL the package definitely works.

However when I run Atom from the application icon I get the error that I sent in and also the error that you closed in issue #8. And when I type code in a Python window there, only Atoms built-in autocomplete pops up, not the Python specific autocomplete.

`which python` yields `/Library/Frameworks/Python.framework/Versions/2.7/bin/python`. That is 2.7.10.

Result of <kbd>option</kbd>+<kbd>command</kbd>+<kbd>I</kbd>:
<img width="432" alt="screen shot 2015-07-27 at 8 48 55 am" src="https://cloud.githubusercontent.com/assets/13447051/8906411/7bbff37e-343c-11e5-9a84-74aa7f9dc41e.png">

**Comment by sadovnychyi** [comment]
This should be fixed when we will implement better interpreter lookup in #66.
Please watch mentioned issue for updates.
