### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by dessant** [sadovnychyi/autocomplete-python#46]
I'm having a python process running `lib/completion.py` which consumes an incresing amount of memory, and it can go beyond 1GB.

I'm using atom 1.0.2 on debian stretch, with autocomplete-python updated. The issue can be reproduced mostly reliably, after a couple of hours of atom usage the pc starts to slow down, and this process stands out with a huge memory allocation.

Have others seen this issue?

**Comment by sadovnychyi** [comment]
It's looks ok for me with 8 gb of memory, but I'll look into exact numbers.

**Comment by dessant** [comment]
Yes, something must be wrong if a process uses more and more memory, without ever freeing any.

**Comment by sadovnychyi** [comment]
I'm closing this since I cannot reproduce it.
