### ISSUE TITLE
Auto importing

### ISSUE THREAD

**Issue by ferdynice** [sadovnychyi/autocomplete-python#48]
Is there any plan to support auto importing (add imports based on functions/classes somewhere in the project)?

**Comment by sadovnychyi** [comment]
Can you explain a bit more detailed please?

**Comment by ferdy-galema** [comment]
Let's say your working on a Django project and you want to use the reverse(...) utility. Normally you'd have to add the following line manually:

`from django.core.urlresolvers import reverse`

and only then you can use the reverse method. It would be very nice if you could just type `reverse` in the code and then the autocompletion will suggest functions that it can find on your pythonpath with that starts or equals `reverse`. Of course this is in addition to the autocomplete items already present with your package. (So you will still see the local variables/methods). The same goes for classes etc.

I'd like to point out that some of the functionalities needed for this function can be inspired by the following packages:

https://atom.io/packages/atom-ctags (build global symbols for use with the symbol browser)
https://atom.io/packages/python-isort (auto sort imports)

**Comment by sadovnychyi** [comment]
Sounds interesting, but cannot say when I will be able to take a look into it. But PRs are welcome :)

**Comment by ferdy-galema** [comment]
Sure! If I will get around to it, I will definitely post updates here. (But not sure if or when).

**Comment by sadovnychyi** [comment]
I'm closing this since I don't think that there are an effective way to implement this.

**Comment by dperetti** [comment]
Looks like Jedi makes it possible ?
http://jedi.jedidjah.ch/en/latest/docs/development.html#imports-modules

**Comment by sadovnychyi** [comment]
I don't think so.

> jedi.evaluate.imports is here to resolve import statements and return the modules/classes/functions/whatever, which they stand for.

This is opposite from resolving an object into list of possible imports. I'm sure there's a way to hack jedi to do it anyway, but I cannot invest my time into it right now. And it maybe bad for performance since we should look *everywhere*.
