### ISSUE TITLE
Can't get autocomplete for module

### ISSUE THREAD

**Issue by ciceroneves** [sadovnychyi/autocomplete-python#49]
Hi there,
First of all sorry if this is not an actual issue but I couldn't find another way to ask that.
I have installed autocomplete-python for Atom (OS X) and I have this small script I am using to test the plugin.
I have imported one module in this script and I was expecting that I would get auto-completion for the functions inside it but that is not happening.
Could you please advise? Is there an special keyboard short cut to force the auto-completion besides ctrl-space?

The module I have imported is located inside /usr/local/lib/python2.7/site-packages/. I have tried to add the path for the module in autocomplete-python Settings as an Extra PATH but it was of no help.

**Comment by sadovnychyi** [comment]
First of all: does autocompletion works for local stuff? Like when you type "im" do you see "import" keyword suggested? If so -- autocomplete works fine. If no -- do you use .py extension for the file you are trying to edit and are you sure that you use Python syntax?

**Comment by ciceroneves** [comment]
Yeah, the "import" suggestion shows up when I type "im"
The extension of the file is .py and I am pretty sure I am using python
syntax.

I am using this simple example here:
https://boto.readthedocs.org/en/latest/getting_started.html#making-connections

But I can't get the autocompletion to call connect_s3

Thanks in advance for the support.

**Comment by patrys** [comment]
Are you using a `virtualenv`? Did you add its python path in the plugin settings?

**Comment by sadovnychyi** [comment]
I'm pretty sure everything should work if you will add `/usr/local/lib/python2.7/site-packages` into extraPaths setting. I'm closing this since it's pretty old but feel free to reply if it's still does not works. Be sure to check that you have desired module at that site-packages directory.
