### ISSUE TITLE
Uncaught Python Provider error: Traceback (most recent call last):  File "/usr/people/jingpeng/.atom/packages/autocomplete-python/lib/completion.py", line 156, in <module>    JediCompletion().watch()  File "/usr/people/jingpeng/.atom/packages/autocomplete-python/lib/completion.py", line 153, in watch    self._process_request(sys.stdin.readline())  File "/usr/people/jingpeng/.atom/packages/autocomplete-python/lib/completion.py", line 145, in _process_request    self._write_response(self._serialize(completions, request['id']))  File "/usr/people/jingpeng/.atom/packages/autocomplete-python/lib/completion.py", line 108, in _serialize    'type': self._get_completion_type(completion),  File "/usr/people/jingpeng/.atom/packages/autocomplete-python/lib/completion.py", line 39, in _get_completion_type    if completion.type not in ['import', 'keyword'] and is_built_in():  File "/usr/people/jingpeng/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 470, in type

### ISSUE THREAD

**Issue by jingpengwu** [sadovnychyi/autocomplete-python#5]
[Enter steps to reproduce below:]
import numpy as np

import matplotlib.pylab as plt

plt.plot(range(10), np.random.randn(10))
plt.show()
plt.

**Atom Version**: 0.196.0
**System**: linux 3.13.0-49-generic
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v0.3.0

### Stack Trace

Uncaught Python Provider error: Traceback (most recent call last):
  File "/usr/people/jingpeng/.atom/packages/autocomplete-python/lib/completion.py", line 156, in <module>
    JediCompletion().watch()
  File "/usr/people/jingpeng/.atom/packages/autocomplete-python/lib/completion.py", line 153, in watch
    self._process_request(sys.stdin.readline())
  File "/usr/people/jingpeng/.atom/packages/autocomplete-python/lib/completion.py", line 145, in _process_request
    self._write_response(self._serialize(completions, request['id']))
  File "/usr/people/jingpeng/.atom/packages/autocomplete-python/lib/completion.py", line 108, in _serialize
    'type': self._get_completion_type(completion),
  File "/usr/people/jingpeng/.atom/packages/autocomplete-python/lib/completion.py", line 39, in _get_completion_type
    if completion.type not in ['import', 'keyword'] and is_built_in():
  File "/usr/people/jingpeng/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 470, in type

```
At /usr/people/jingpeng/.atom/packages/autocomplete-python/lib/provider.coffee:39

undefined
```

### Commands

```
     -0:33.1.0 application:open-file (atom-text-editor.editor)
 41x -0:19.9.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:16 core:page-down (atom-text-editor.editor.is-focused.autocomplete-active)
 54x -0:14.6.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
  4x -0:06.5.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:04.0 core:move-up (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "projectHome": "/usr/people/jingpeng/workspace",
    "disabledPackages": [
      "vim-mode",
      "autocomplete-plus-python-jedi"
    ]
  },
  "autocomplete-python": {}
}
```

### Installed Packages

```coffee
# User
atom-runner, v2.3.0
autocomplete-plus, v2.12.1
autocomplete-python, v0.3.0
language-julia, v0.7.2

# Dev
No dev packages
```

**Comment by sadovnychyi** [comment]
While I cannot fix the root of this exception, the autocompletion should continue to work after such errors in >0.3.1. You are still able to see the jedi errors in the atom's console. (command+option+I)
