### ISSUE TITLE
.pth not being imported

### ISSUE THREAD

**Issue by simoncoulton** [sadovnychyi/autocomplete-python#50]
I've got a couple of .pth files that I use for local projects that sit within my site-packages folder, however for some reason it doesn't seem to autocomplete them. If I manually add each path that is within the .pth file it works. These do work with Jedi within Sublime Text.

Config is as follows:
```
"autocomplete-python":
    showProviderErrors: true
    extraPaths: "/Users/simon/.virtualenvs/3.4/lib/python3.4/site-packages"
    useSnippets: "required"
    addBracketAfterFunction: true
```

**Comment by sadovnychyi** [comment]
Should be fixed since now you can use python binaries from virtual environments.

**Comment by simoncoulton** [comment]
Awesome, thanks mate :+1:

**Comment by sadovnychyi** [comment]
Let me know if it doesn't.
