### ISSUE TITLE
what's wrong with my Atom packages?

### ISSUE THREAD

**Issue by ilumer** [sadovnychyi/autocomplete-python#53]
![qq 20150817160602](https://cloud.githubusercontent.com/assets/10941253/9300557/e4c00fb2-44f9-11e5-8296-0e727713774a.png)
I only use this package and linter,i can not to solve this problem

**Comment by sadovnychyi** [comment]
Can you provide full tracelog please? Is it does not works at all or you only saw this once?

**Comment by ilumer** [comment]
![image](https://cloud.githubusercontent.com/assets/10941253/9355952/06e3c3ce-46b0-11e5-816c-ea5baa8354e0.png)
this is my code
    import urllib.request
    import urllib.parse
    import http.cookiejar

   cookie=http.cookiejar.LWPCookieJar()
   opener=urllib.request.build_opener(urllib.request.HTTPCookieProcessor(cookie))
   urllib.request.install_opener(opener)

**Comment by sadovnychyi** [comment]
This is likely to be a bug in Jedi and you shouldn't see such errors unless you have `outputProviderErrors` setting set to True. By default it set to False.
