### ISSUE TITLE
Need help about autocomplete-python

### ISSUE THREAD

**Issue by lyosen** [sadovnychyi/autocomplete-python#54]
I have some problems

autocomplete-python unable to find python executable: please set the path to python directory manually in the package settings and restart your editor. If issue persists please report it at https://github.com/sadovnychyi/autocomplete-python/issues/new

**Comment by sadovnychyi** [comment]
`please set the path to python directory manually in the package settings and restart your editor`
Did you try it? What is the output of `which python`?
