### ISSUE TITLE
PicklingError occurs at seemingly random times

### ISSUE THREAD

**Issue by SpainTrain** [sadovnychyi/autocomplete-python#55]
Once every couple hours, I suddenly receive a never-ending (until I restart Atom) set of these errors - "PicklingError: Can't pickle <type 'member_descriptor'>: attribute lookup __builtin__.member_descriptor failed"

![selection_007](https://cloud.githubusercontent.com/assets/380032/9375560/338eaf04-46d0-11e5-8ab0-ce67d378d37f.png)

I have not yet noticed any pattern related to my behavior or the files open when these occur.

OS: Ubuntu 14.10 3.16.0-44-generic #59-Ubuntu SMP Tue Jul 7 02:07:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Atom: 1.0.7
autocomplete-python: 0.5.3

**Comment by sadovnychyi** [comment]
This is likely to be a bug in Jedi and you shouldn't see such errors unless you have `outputProviderErrors` setting set to True. By default it set to False.
