### ISSUE TITLE
wish to support two or more extra path

### ISSUE THREAD

**Issue by ethe** [sadovnychyi/autocomplete-python#58]
i usually have lots of projects with its own virtual environment, but it seems like this packages can only set one extra path. it is too troublesome to switch between one and another virtual environment

**Comment by sadovnychyi** [comment]
Why only one?

You can set up as many as you want using semicolon as delimiter. And if your virtual env has the same relative path in each project you can define just one with $PROJECT prefix.

For me it looks like this:
```
$PROJECT/env/lib/python2.7/site-packages;/usr/local/google_appengine
```

**Comment by ethe** [comment]
thx, i used commas rather than semicolons...
