### ISSUE TITLE
exit with code 126, signal null & Uncaught Error: This socket is closed.

### ISSUE THREAD

**Issue by laike9m** [sadovnychyi/autocomplete-python#63]
When I open atom, it pops up the first window says: `exit with code 126, signal null`.
Then when I type something, the `Uncaught Error: This socket is closed.` shows up.

<img width="453" alt="2015-09-23 4 47 29" src="https://cloud.githubusercontent.com/assets/2592205/10040971/273ec8c0-6213-11e5-93b8-509843a0a342.png">

I'm using atom 1.0.15 on OSX 10.10

**Comment by sadovnychyi** [comment]
This should be fixed when we will implement better interpreter lookup in #66.
Please watch mentioned issue for updates.
