### ISSUE TITLE
Support multiple paths to different named binaries

### ISSUE THREAD

**Issue by posita** [sadovnychyi/autocomplete-python#66]
Right now, [`autocomplete-python.pythonPath`](https://github.com/sadovnychyi/autocomplete-python/blob/740238ee43222dd25a6ef7d3de5aa7275a7636f4/lib/provider.coffee#L17) and [`autocomplete-python.pythonExecutable`](https://github.com/sadovnychyi/autocomplete-python/blob/740238ee43222dd25a6ef7d3de5aa7275a7636f4/lib/provider.coffee#L18) are separate. The former can have multiple values (searched in order, separated by `;`s). The latter is fixed with a single value.

This makes sense, because `autocomplete-python.pythonPath`'s values are merely prepended to one's `PATH`.

But, I might want to have a setting where I want to degrade from the following:

* `$PROJECT/.venv/bin/python` - uses python2.7
* `python3.4` - default to system-wide Python 3.4 (which is not installed as `.../bin/python`

I can't do that with the current settings.

(See also #25.)

**Comment by posita** [comment]
Actually, I probably *can* work-around it by doing the following (on real OSes):

```sh
% ln -s $( which python3.4 ) "${HOME}/.atom/special/python"
```

Then:

```js
autocomplete-python.pythonPath = "$PROJECT/.venv/bin;/[HOME]/bin";
autocomplete-python.pythonExecutable = "python";
```

I don't *necessarily* want `"${HOME}/.atom/special/python"` in my path though, and this (probably) won't work on Windoze.

As an aside, it might be nice to support full environment variable expansion in these strings (where `PROJECT` is set from Atom's project directory), so I could do something like this:

```js
autocomplete-python.pythonPath = "${PROJECT}/.venv/bin;/${HOME}/bin";
autocomplete-python.pythonExecutable = "python";
```

**Comment by SpainTrain** [comment]
@sadovnychyi LMK if you have any interest in collaborating on an npm module that encapsulates this kind of logic in a library.  I was planning to implement this anyway for https://github.com/AtomLinter/linter-pylint/issues/62.  It would probably be nice for Python devs using atom to have consistency across plugins.

CCing other python plugin authors/maintainers:

@MichaelAquilina @saravanan-k90 @bsnux

**Comment by posita** [comment]
@SpainTrain, maybe consider a patch to Atom core (perhaps to the [`shell` module](https://github.com/atom/electron/blob/master/docs/api/shell.md))? This seems like a widely-tackled problem....

**Comment by SpainTrain** [comment]
good point.  I could still see a python-specific lib for handling things like `$PYTHONPATH`, which has caused some pain (https://github.com/AtomLinter/linter-pylint/pull/61)

**Comment by MichaelAquilina** [comment]
@SpainTrain I would be interested to see this done. It's pretty much something that needs to be copied across every atom plugin I write that interacts with python. 

Abstracting it away into an npm library or into Atom core itself will be a major help in cleaning up common code.

**Comment by sadovnychyi** [comment]
@SpainTrain yeah, npm module would be awesome for this.

I would love to hear some advices about it from atom devs as well. @benogle @joefitzgerald

**Comment by sadovnychyi** [comment]
@patrys wrote interesting thing possible related to this:

It does not currently do anything other than show the list of Python binaries found and to make it work we'd have to combine the settings for path and binary name. That in turn would make it harder to configure the plugin for multiple projects but there is a package named `project-manager` that exposes an API we could use to set the interpreter for each project separately.

You can see the current code at https://github.com/patrys/autocomplete-python/tree/feature/interpreter-chooser

**Comment by patrys** [comment]
My idea was to replicate what PyCharm does and allow the user to pick a path without having to enter it by hand unless it's unusually special. I can certainly see value in sharing this code between plugins, it might even live in a separate plugin that exposes the path and takes care of the rest (UI, interacting with `package-manager` if available etc.) so the poor user does not have to change the path in five places.

**Comment by posita** [comment]
FWIW, I came across these:

* https://www.npmjs.com/package/dotenv
* https://www.npmjs.com/package/expand-var

The `.env` is a little different than the discussed approaches.

As an aside (probably not very relevant here):

* http://blog.atom.io/2014/09/16/new-event-subscription-api.html (generic event related observations, e.g., to signal a change in a user setting)

**Comment by sadovnychyi** [comment]
@posite what if we will automatically look for python binaries inside of your project and try to use it instead of global one? If nothing found – fallback on global one. I don't see a way to store config for per project binaries. Is there are any cases when you have multiple python binaries inside of one project?

**Comment by patrys** [comment]
There is a project manager plugin that exposes APIs for per-project configuration.

**Comment by sadovnychyi** [comment]
But with project manager you can just adjust executable paths for each project, isn't? 
```
projectmanager:
  title: 'My project'
  paths: [
    '/path/to/project-manager'
  ]
  settings:
    '*':
      "autocomplete-python":
        extraPaths: ""
        pythonExecutable: "python3"
```

**Comment by posita** [comment]
> ... what if we will automatically look for python binaries inside of your project and try to use it instead of global one? If nothing found – fallback on global one.

I think this would work, so long as one could configure a general project-relative path. For example:

```js
autocomplete-python.projectPythonPath = ".venv/bin/python"; // relative paths are treated as relative to project directory
autocomplete-python.globalPythonPath = "python"; // default if the above doesn't resolve to an executable
```

This would look to `[PROJECT_DIR]/.venv/bin/python` first, and fall back to `python` if that didn't resolve. That way you could override it on a per-project basis by creating or linking `.venv` (or whatever you set it to) at the project root level.

Something like this would play particularly well with per-project `virtualenv`s:

```sh
% cd [PROJECT_DIR]
% virtualenv --python=... .venv
...
% .venv/bin/pip install pyflakes pylint jedi
...
% .venv/bin/pip install -r requirements.txt
...
% .venv/bin/pip install -e .
...
```

Or even:

```sh
% cd [PROJECT_DIR]
% mkvirtualenv -a "${PWD}" --python=... "$( basename "${PWD}" )"
...
% ln -s "${VIRTUAL_ENV}" .venv
% pip install pyflakes pylint jedi
...
% pip install -r requirements.txt
...
% pip install -e .
...
```

:+1:

**Comment by patrys** [comment]
Yeah, if we could set the executable to "$PROJECT/.venv/bin/python" then things would work without exposing system packages to Jedi.

Jedi itself could be injected by appending an extra path to `sys.path`—perhaps at the end to allow local Jedi to take preference?

**Comment by posita** [comment]
I'm imagining something analogous to this (see <https://nodejs.org/api/fs.html> and <https://nodejs.org/api/path.html>):

```js
var path = require('fs');
var path = require('path');

function (...) {
    var project_dir = ...;
    var project_python = autocomplete-python.projectPythonPath;

    if (! path.isAbsolute(autocomplete-python.projectPythonPath)) {
        project_python = path.join(project_dir, project_python);
    }

    var stats = fs.statSync(project_python);

    if (stats.isFile()
            && fs.accessSync(path, fs.X_OK)) {
        return project_python;
    }

    return autocomplete-python.globalPythonPath;
}
```

**Comment by sadovnychyi** [comment]
@posita would you like to test my [PR](https://github.com/sadovnychyi/autocomplete-python/pull/125)?

Add new config with optional semicolon separated list of paths to python executables (including executable names), where the first one will take higher priority over the last one. By default autocomplete-python will automatically look for venvs inside of your project and try to use them as well as try to find global python executable.
Use $PROJECT variable for project specific paths to point on executables in virtual environments.

For example: `$PROJECT/env/bin/python3;/usr/bin/python` will fall back on `/usr/bin/python` for projects without venv, but will use env/bin/python3 when possible.

@posita for your specific case you could just write `$project/.venv/bin/python` in pythonPaths. It should fall back on global one for projects without venvs.

**Comment by posita** [comment]
@sadovnychyi, can you remind me again how to install an Atom package by path or repo? The following doesn't seem to work for me: :disappointed: 

```sh
% rm -fr ~/.atom/{.apm,packages}/autocomplete-python
...
% git clone https://github.com/sadovnychyi/autocomplete-python.git
% cd autocomplete-python
% git pull --all --tags
...
% git checkout interpreter-chooser
Branch interpreter-chooser set up to track remote branch interpreter-chooser from origin.
Switched to a new branch 'interpreter-chooser'
% apm install
Installing modules ✓
% ls -al ~/.atom/{.apm,packages}/autocomplete-python
ls: /.../.atom/.apm/autocomplete-python: No such file or directory
ls: /.../.atom/packages/autocomplete-python: No such file or directory
```

:confused:

**Comment by SpainTrain** [comment]
you want `apm link`.  Like this - https://github.com/atom/apm/issues/355#issuecomment-99210591

**Comment by posita** [comment]
@SpainTrain: Thanks!

Apparently, now I'm bumping up against #98: :confused:

![screen shot 2015-12-02 at 15 28 59](https://cloud.githubusercontent.com/assets/222581/11547538/7c18e844-9909-11e5-8381-5aa24a4b783e.png)

**Comment by SpainTrain** [comment]
hrm, try just using `npm install` in the project dir.

**Comment by posita** [comment]
> hrm, try just using npm install in the project dir. 

Um, doesn't this pollute my `npm` installation with Atom packages? That seems a little excessive, no?

Okay, I did this (after quitting Atom):

```sh
% rm -fr ~/.atom/{.apm,packages}/autocomplete-python
% rm -fr ~/.npm/autocomplete-python
% git clone https://github.com/sadovnychyi/autocomplete-python.git
% cd autocomplete-python
% git pull --all --tags
...
% git checkout interpreter-chooser
Branch interpreter-chooser set up to track remote branch interpreter-chooser from origin.
Switched to a new branch 'interpreter-chooser'
% npm install
...
% apm link .
.../.atom/packages/autocomplete-python -> .../autocomplete-python
```

When I start Atom again, it looks like it has the old 0.10.7 settings interface. :rage: :confounded: I don't know where it's coming from.

I'd love to help test the PR, but I need some way to be able to do that. :confused: How do Atom package developers do this?

**Comment by sadovnychyi** [comment]
clone & apm install & apm link should work.. Instead of linking, you can
simply copy and replace folder in your atom packages directory. Be sure to
run apm install to install dependencies. Not sure that npm install does
exactly the same.

**Comment by SpainTrain** [comment]
> Not sure that npm install does
> exactly the same.

```
$ apm help install

If no package name is given then all the dependencies in the package.json
file are installed to the node_modules folder in the current working
directory.
```

`npm install` does _exactly_ the same thing.  However, apm@1.4.0 wraps npm@2.13.3, so it's an older version of npm being used via npm's API, which is more bug-prone.  Better to just use `npm install`.

**Comment by SpainTrain** [comment]
> Um, doesn't this pollute my npm installation with Atom packages?

I'm not sure I totally understand this.  `npm install` just reads dependencies from `package.json` and installs them into a directory `node_modules` in the current dir.  Maybe you are thinking of `npm install -g`?  Even so, npm and apm use different registries, so `npm` will never install apm packages anywhere.

As @sadovnychyi mentions, clone & apm install (or npm install) & apm link should work.  In the project dir, try bumping the version number in package.json, then reload atom, then search for the package in settings/preferences.  Does it show the updated version number? If so, it is loading the code from the git repo and that old settings interface is a different issue.  If not, there is something very strange going on with your atom install that we'd need to dig into further.

**Comment by SpainTrain** [comment]
oh, another thing you can do is just bring up dev tools in atom (same hotkey as Chrome) and in the "sources" tab find the source atom loaded for autocomplete-python to see if it is what you expect.

**Comment by posita** [comment]
Thanks @sadovnychyi and @SpainTrain for your help. My apologies for my ignorance. :disappointed: Here's what I finally did:

```sh
% rm -frv ~/.atom/{.apm,packages}/autocomplete-python ~/.npm/autocomplete-python
...
% cd ~/.atom/packages
% git clone https://github.com/sadovnychyi/autocomplete-python.git
% cd autocomplete-python
% git pull --all --tags
...
% git checkout interpreter-chooser
Branch interpreter-chooser set up to track remote branch interpreter-chooser from origin.
Switched to a new branch 'interpreter-chooser'
% apm install
Installing modules ✓
% ls node_modules
atom-slick
atom-space-pen-views
fuzzaldrin
selector-kit
% atom.sh
% mkdir .../foo
% cd .../foo
% touch test.py
% virtualenv --python=pypy .venv-pypy
Running virtualenv with interpreter /Users/matt/.site/bin/pypy
New pypy executable in .venv-pypy/bin/pypy
Installing setuptools, pip, wheel...done.
% .venv-pypy/bin/pip install pycoin
Collecting pycoin
Installing collected packages: pycoin
Successfully installed pycoin-0.62
% virtualenv --relocatable .venv-pypy
...
% ln -sv .venv-pypy .venv
.venv -> .venv-pypy
% .venv/bin/python -c 'import pycoin as test_module ; print(test_module.__file__)'
.../foo/.venv/site-packages/pycoin/__init__.pyc
% python -c 'import pycoin as test_module ; print(test_module.__file__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pycoin
% atom.sh . # wait for project window to open
```

![screen shot 2015-12-02 at 19 44 33 1](https://cloud.githubusercontent.com/assets/222581/11551446/37ff1bcc-992e-11e5-885d-9c8a4bf5b75c.png)

![screen shot 2015-12-02 at 19 44 33 2](https://cloud.githubusercontent.com/assets/222581/11551448/3afa5d46-992e-11e5-9fd0-7181ccdf785c.png)

```sh
% atom.sh test.py
```

![screen shot 2015-12-02 at 19 44 58](https://cloud.githubusercontent.com/assets/222581/11551390/873173bc-992d-11e5-81ce-4edd6c41e4c0.png)

```sh
% ps -o pid,ppid,pgid,pri,tt,stat,time,%cpu,%mem,start,command -x -ww | grep -i python
 6120  5736  4647  31   ??  S      0:01.56   0.0  0.6  7:44PM .../foo/.venv/bin/python ~/.atom/packages/autocomplete-python/lib/completion.py
 6169 95903  6168  31 s006  S+     0:00.00   0.0  0.0  7:45PM grep -i python
% killall Python python
% rm .venv
```

![screen shot 2015-12-02 at 19 46 44](https://cloud.githubusercontent.com/assets/222581/11551396/903edc4c-992d-11e5-9243-3bbcd6f3d2e7.png)

```sh
% psx -ww | grep -i python
 6272  5736  4647  31   ??  S      0:00.79   0.0  0.2  7:46PM ~/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python ~/.atom/packages/autocomplete-python/lib/completion.py
 6312 95903  6311  31 s006  S+     0:00.00   0.0  0.0  7:48PM grep -i python
```

@sadovnychyi: LGTM. (It works as advertised.) I have a few (hopefully constructive) suggestions that I'll leave in subsequent comments.

**Comment by posita** [comment]
Consider eliminating `Python Executable` and `Python Path` in favor of the new `Python executable paths`:

![screen shot 2015-12-02 at 19 44 33](https://cloud.githubusercontent.com/assets/222581/11551572/43dbf874-992f-11e5-8c25-1e6e4d510915.png)

**Comment by sadovnychyi** [comment]
Those old settings already removed actually, not sure why you can see them.
I will definitely follow your advices after making it work properly on
windows.

On Thu, Dec 3, 2015 at 12:06 PM, Matt Bogosian (formerly @mbogosian) <
notifications@github.com> wrote:

> Reopened #66
> <https://github.com/sadovnychyi/autocomplete-python/issues/66>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sadovnychyi/autocomplete-python/issues/66#event-480994804>
> .
>



--

**Comment by SpainTrain** [comment]
Doing new things is quite literally the only way to learn =-)  Glad it finally worked, though it is still strange that linking wasn't working for you.

If you ever need to do plugin dev again, myself or someone in the atom slack can probably help figure out what's up with linking - https://atomio.slack.com/

**Comment by posita** [comment]
> Doing new things is quite literally the only way to learn =-)

True. True.

> ... though it is still strange that linking wasn't working for you ...

I am 99% confident this was a [PEBCAK](https://en.wiktionary.org/wiki/PEBCAK) situation.

Thanks for the help and the invitation for more (for when I am ready to embarrass myself again)! My apologies for hijacking part of this thread for Atom dev tech support! :disappointed:

**Comment by posita** [comment]
> If you ever need to do plugin dev again, myself or someone in the atom slack can probably help figure out what's up with linking - https://atomio.slack.com/

It looks like that's a private team (limited to GH, Adobe, Facebook, or Microsoft). But I appreciate the sentiment. :grin:

**Comment by SpainTrain** [comment]
I gave the wrong link!  https://discuss.atom.io/t/join-us-on-slack/16638

It's definitely for community support.  I don't work for any of those companies, just help maintain a couple linters.  The community there is very good/open, so ask anything! (plus atom is so new, everyone is a n00b :wink: )

**Comment by patrys** [comment]
By the way, since `$PROJECT` only makes sense at the very beginning of the path, couldn't we replace it with `./` to make it obvious that the path is relative?

**Comment by sadovnychyi** [comment]
Hm, looks like yes, we could.

**Comment by posita** [comment]
> couldn't we replace it with `./` to make it obvious that the path is relative?

I kind of liked this at first, but the more I thought about it from the perspective of a new user, the more I asked myself, "relative to what?" `$PROJECT` may be kind of a hack (it looks like a shell variable, but it's really a string replacement), but at least it's explicit about where it's looking. Stylistically, it might be more appropriate to use something like `[FOO]` or `__FOO__` instead of `$FOO` to avoid such confusion, but I do like spelling out *something* for the user that says, "this is going to be replaced with your project root, not any other path."

**Comment by patrys** [comment]
Well, a project can have [many roots](https://github.com/atom/atom/blob/v1.2.3/src/project.coffee#L141) and `lorem$PROJECTipsum` does not make much sense.

**Comment by posita** [comment]
> a project can have [many roots](https://github.com/atom/atom/blob/v1.2.3/src/project.coffee#L141)

Crap. I forgot about this. :disappointed: But an open buffer only belongs to zero or one roots, correct? (My understanding of multiple roots is very limited.)

> `lorem$PROJECTipsum` does not make much sense

I absolutely agree with this. :grin:

**Comment by patrys** [comment]
I'm not sure you can ask for the root of the current open buffer, project paths will return a list of all directories added to the project. You could ask for the file's path and look for matches (but of course one is still able to open a file that lays outside all of them).
