### ISSUE TITLE
Integrate goto definition with symbols browser

### ISSUE THREAD

**Issue by ferdynice** [sadovnychyi/autocomplete-python#71]
Integrating the goto-definition with the symbol browser makes for nice navigation. (Going to declaration and back with the symbol commands). Not sure if this is possible.

Also searching Python symbols would be possible.

**Comment by sadovnychyi** [comment]
As @patrys explained we have to wait for atom/symbols-view#95

**Comment by eMerzh** [comment]
hi , 

i just sumble upon  hyperclick package .. it might be a good start for such a "goto" feature no?

**Comment by sadovnychyi** [comment]
@eMerzh it is not related with symbols browser integration, but I like your idea.

**Comment by sadovnychyi** [comment]
It seems like no progress for symbols provider API, so I'm going to close this for now.
