### ISSUE TITLE
lacks intelligence on arguments of a function

### ISSUE THREAD

**Issue by donraj** [sadovnychyi/autocomplete-python#73]
say a fn f(max_length, is_overload=False)

The package correctly hints the fn name, however, it does not autocomplete any argument name. 

This feature is present in autocomplete-plus python and also sublimecodeintel.

**Comment by sadovnychyi** [comment]
It works just well for me, but note that this feature is disabled by default, you have to turn it on in package settings:
![image](https://cloud.githubusercontent.com/assets/193864/10273778/3dcb04d8-6b68-11e5-910d-09dc28a84a03.png)

![sample](https://cloud.githubusercontent.com/assets/193864/10273791/8126f44e-6b68-11e5-9dab-cb76ad0559b8.gif)

**Comment by donraj** [comment]
My bad. Thanks so much!
