### ISSUE TITLE
Fails to autocomplete methods

### ISSUE THREAD

**Issue by DanielJoyce** [sadovnychyi/autocomplete-python#76]
``` python
class UuidGen:
''' UUID Generator
'''
    _chars = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

    def __init__(self, seed):
        self.rand = random.Random(x=None)
        self._uuidPrefix = self._getRandomString()

    def _getRandomString(self):
        return string.join([self.rand.choice(UuidGen._chars),
                            self.rand.choice(UuidGen._chars),
                            self.rand.choice(UuidGen._chars),
                            self.rand.choice(UuidGen._chars),
                            self.rand.choice(UuidGen._chars)], "")

    def generate(self):
        return string.join([self._uuidPrefix,
                            self._getRandomString(),
                            self._getRandomString(),
                            self._getRandomString()], "-")

ugen = UuidGen(None)

ugen. # ctrl-space fails here, results in ugenself.

```

Autocomplete does kinda work for imports and local classes, but breaks on instance methods.

Atom: 1.0.19
autocomplete-python: 0.6.2
python: 2.7.6
uname -a : 

Linux lnx-daniel 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

/etc/lsb-release: 

DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.1
DISTRIB_CODENAME=rebecca
DISTRIB_DESCRIPTION="Linux Mint 17.1 Rebecca"

**Comment by DanielJoyce** [comment]
I take it backs, it works in some cases but not others. May have to do with various features a class uses.

**Comment by DanielJoyce** [comment]
Personal idiocy.

Errors in code, but there really is no feedback where I am messing up. Don't know if thats a jedi issue or we need a linter...?

**Comment by sadovnychyi** [comment]
Of course it's better to use linter. I can change the logic how the
completion is appended (to add a dot in that your case), but if there are
no completions offered -- its likely to be Jedi issue.

**Comment by DanielJoyce** [comment]
So yeah it was the winter settings. At some point it seems another plugin
disabled longer error display settings. I went and turned them all in and
it works good.

On Fri, Oct 9, 2015, 18:21 Dmitry Sadovnychyi <notifications@github.com>
wrote:

> Of course it's better to use linter. I can change the logic how the
> completion is appended (to add a dot in that your case), but if there are
> no completions offered -- its likely to be Jedi issue.
>
> On Sat, Oct 10, 2015, 00:21 Daniel <notifications@github.com> wrote:
>
> > Personal idiocy.
> >
> > Errors in code, but there really is no feedback where I am messing up.
> > Don't know if thats a jedi issue or we need a linter...?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/sadovnychyi/autocomplete-python/issues/76#issuecomment-146937784
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sadovnychyi/autocomplete-python/issues/76#issuecomment-147020216>
> .
>
-- 
Daniel Joyce

The meek shall inherit the Earth, for the brave will be among the stars.
