### ISSUE TITLE
autocomplete support for compiled .dll libraries

### ISSUE THREAD

**Issue by mostaphaRoudsari** [sadovnychyi/autocomplete-python#77]
Is there any way that the code can be modified to support autocomplete for binary libraries. I tested it for a couple of libraries including clr and it doesn't work.

```python
import clr
clr.#doesn't show up anything#
```
Thanks!

**Comment by sadovnychyi** [comment]
Since completions are provided by Jedi, it's better to write feature request there.

https://github.com/davidhalter/jedi

This package is just a wrapper around their API.
