### ISSUE TITLE
auto-complete not finding new packages

### ISSUE THREAD

**Issue by ldelossa** [sadovnychyi/autocomplete-python#78]
Hey guys,

I installed a few new packages via the pip3 command. In Atom I cannot get autocomplete/jedi to "find" the newly installed packages. I can write a script using the package's elements - but I do not get any auto complete features. Is there anyway to fix this?

**Comment by sadovnychyi** [comment]
Have you added your site packages folder into extraPaths setting?

**Comment by ldelossa** [comment]
I haven't touched any configuration I did a quick look at the read me page
but didn't see what you're mentioning

**Comment by sadovnychyi** [comment]
You can find it in package settings. I'll add this into readme to make it clear. 

```
Semicolon separated list of modules to additionally include for autocomplete.
      You can use $PROJECT variable here to include project specific folders like virtual environment.
      Note that it still should be valid python package.
      For example: $PROJECT/env/lib/python2.7/site-packages.
```

**Comment by ldelossa** [comment]
I'm sorry - but where can I get to package settings? I'm looking at the source and I don't see where to edit.

**Comment by sadovnychyi** [comment]
Go into Atom Settings -> Packages, look for autocomplete-python and click settings.

**Comment by ldelossa** [comment]
wow didn't even know that existed. Works like a charm! thanks a ton that was killing me.
