### ISSUE TITLE
Porting the project to Brackets?

### ISSUE THREAD

**Issue by abdelouahabb** [sadovnychyi/autocomplete-python#79]
Hi,
This is a wonderful plugin, but could you make a port to Brackets ?

**Comment by sadovnychyi** [comment]
Sorry, I don't have any plans to use brackets. It is based on [Jedi](https://github.com/davidhalter/jedi) and maybe you could ask somebody there to do it.

License of this package allows to use its source code anywhere you want as long as you keep it open sourced, just in case if somebody would like to use it.

**Comment by abdelouahabb** [comment]
Thank you :D I will see
