### ISSUE TITLE
Incompatible with pyenv

### ISSUE THREAD

**Issue by ftiasch** [sadovnychyi/autocomplete-python#80]
It seems that the plugin is not compatible to work with [pyenv](https://github.com/yyuu/pyenv).

```
autocomplete-python provider exit.
exit with code 1, signal null

python-tools experienced an unexpected exit.
exit with code 1, signal null
```

**Comment by sadovnychyi** [comment]
Have you tried to configure your `Path to python directory` setting?

**Comment by ftiasch** [comment]
@sadovnychyi Yes.  In `config.cson` there is `pythonExecutable: "/Users/ftiasch/.pyenv/shims/python"`

**Comment by sadovnychyi** [comment]
Sorry for confusing, but it should point on the **directory••. Try to use `"/Users/ftiasch/.pyenv/shims"`

**Comment by sadovnychyi** [comment]
Ah, actually `"/Users/ftiasch/.pyenv/shims"` should be set for `pythonPath`.
And you can keep `pythonExecutable` setting empty as its used to set python executable name, which is by default `python` but could be `python3` in some cases.
