### ISSUE TITLE
auto-complete chooses abs(number) way too easily

### ISSUE THREAD

**Issue by Dowwie** [sadovnychyi/autocomplete-python#82]
I've had to delete abs(number) from my code so many times that it has finally compelled me to come here and share my grievances.  

abs(number) is the first option in autocomplete and it is practically forced onto me as I type.  PLEASE make autocomplete less automatic to prevent this from happening!

**Comment by sadovnychyi** [comment]
Can you explain a bit more about your problem please?

Are you getting autocompleted when you don't want to and you accidently confirm completion by pressing enter? Have you tried to set a key to confirm suggestion to "tab" only?
![image](https://cloud.githubusercontent.com/assets/193864/10533799/e4ae0480-7400-11e5-83cd-d37e8713270d.png)

What do you mean by asking me to make it less automatic? Do not trigger suggestions unless you press a specific key or what?

**Comment by Dowwie** [comment]
No I haven't tried that.  Where can I find it?

yes-- Less automatic as in I want to press a specific key combination to initiate an autocomplete suggestion

**Comment by sadovnychyi** [comment]
All you need to do is to properly configure your autocomplete-**plus**. Go to atom settings -> packages -> autocomplete-plus settings.

![image](https://cloud.githubusercontent.com/assets/193864/10597880/f07b40c0-7725-11e5-9a10-742e76b34e53.png)


![image](https://cloud.githubusercontent.com/assets/193864/10597878/ec140666-7725-11e5-8ec7-e6e624389722.png)
