### ISSUE TITLE
Function arguments not showing during autocompletion

### ISSUE THREAD

**Issue by Stefan-Code** [sadovnychyi/autocomplete-python#84]
When autocompleting a function like pickle.dumps, it would be nice to see what arguments were used in the function definition. Right now it looks like this for me:
![autocompleting pickle] (http://i.imgur.com/dgGQO3v.png)
So it should also display:
`dump(obj, file, protocol)` somewhere

**Comment by sadovnychyi** [comment]
Please look for package setting to complete arguments.

**Comment by sadovnychyi** [comment]
Its, actually, visible for me:

![image](https://cloud.githubusercontent.com/assets/193864/10570521/6e92f5d0-7667-11e5-97fc-b2ebe65b7851.png)

**Comment by Stefan-Code** [comment]
Very weird. Is there some kind of cache I can clear? Or do you have any other ideas? Thanks.

**Comment by sadovnychyi** [comment]
Its also weird that you can see doc strings, while I can see only arguments. I'll try to investigate this once I got a minute.

**Comment by sadovnychyi** [comment]
Should be fixed in 0.7.0.
