### ISSUE TITLE
$0 appended to every suggestion

### ISSUE THREAD

**Issue by beefybug** [sadovnychyi/autocomplete-python#91]
Every time I autocomplete a suggestion, it appends '$0' behind the suggestion.

![image](https://cloud.githubusercontent.com/assets/7582689/10647022/3087bcf0-7804-11e5-98e0-4db9e4e67477.png)

**Comment by sadovnychyi** [comment]
Wow, this is strange. Can you give me more information about your system? Can you try to reinstall the package?

**Comment by beefybug** [comment]
Hi, I did a full reinstall and apparently that resolved the issue. :)
