### ISSUE TITLE
suggest for autocomplete function parameters is all

### ISSUE THREAD

**Issue by alvinyangyang** [sadovnychyi/autocomplete-python#93]
autocomplete-python is very useful and It's very helpful to me.
in v.0.7.0

~/.atom/packages/autocomplete-python/lib/jedi/evaluate/compiled/__init__.py   line 96

to change from 
if len(parts) > 1
into
if len(parts) > 1 and parts != 'self' and parts != 'cls':

maybe useful method & class method:
autocomplete function parameters is all

**Comment by sadovnychyi** [comment]
Can you give more explanation please?
And if you want to improve [Jedi](https://github.com/davidhalter/jedi) it's better to send Pull Request directly to them.

Glad you found it useful anyway!

**Comment by alvinyangyang** [comment]
Why is this


Thank’s for your job


原始邮件
发件人:Dmitry Sadovnychyinotifications@github.com
收件人:sadovnychyi/autocomplete-pythonautocomplete-python@noreply.github.com
抄送:alvinyangyangimagine.alvin.yang@qq.com
发送时间:2015年10月27日(周二) 13:50
主题:Re: [autocomplete-python] suggest for autocomplete functionparameters is all (#93)


Can you give more explanation please?
 And if you want to improve Jedi it's better to send Pull Request directly to them.
Glad you found it useful anyway!

**Comment by sadovnychyi** [comment]
Ok, it looks like there are some cases where "cls" and "self" are getting completed as arguments. 
![image](https://cloud.githubusercontent.com/assets/193864/10776389/e3d47248-7d4b-11e5-8626-e84dcd740aa0.png)

But it seems like you are using old version. Can you update the package and try to reproduce it again?
If you can reproduce it with new version – please give me sources of c4d package so I can try it by myself.

**Comment by alvinyangyang** [comment]
I try v0.9.0  autocomplete Function Parameters not work for me,:)

 I send test.py file to you, in any modules is same case, in 3 times , ’self' is show, I will use this call in a lot of work. 

Thank you sadovnychyi

**Comment by sadovnychyi** [comment]
@alvinyangyang please send it directly to my email, not using github since attachments are not allowed here.

**Comment by sadovnychyi** [comment]
![image](https://cloud.githubusercontent.com/assets/193864/10777404/1901eaa4-7d56-11e5-831d-5ab4125a1718.png)

From your sample, when I'm open a bracket after `new.get` only `arg` getting autocompleted, no `self`.
