### ISSUE TITLE
Uncaught SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by fchevitarese** [sadovnychyi/autocomplete-python#95]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0-beta1
**System**: Linux Mint
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v0.9.0

### Stack Trace

Uncaught SyntaxError: Unexpected token {

```
At file:///usr/share/atom-beta/resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2Fhome%2Ffred%2FDropbox%2Fprojetos%2Fpython%2Fdatagoal-2.0.0%2Fdatagoal%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%7D%5D%2C%22bootstrapScript%22%3A%22%2Fusr%2Fshare%2Fatom-beta%2Fresources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2Fusr%2Fshare%2Fatom-beta%2Fresources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%221.1.0-beta1%22%2C%22shellLoadTime%22%3A487%2C%22initialPaths%22%3A%5B%22%2Fhome%2Ffred%2FDropbox%2Fprojetos%2Fpython%2Fdatagoal-2.0.0%2Fdatagoal%22%5D%7D:2

SyntaxError: Unexpected token {
    at Object.parse (native)
    at [object Object].module.exports._deserialize (/home/fred/.atom/packages/autocomplete-python/lib/provider.coffee:122:21)
    at provider.BufferedProcess.stdout (/home/fred/.atom/packages/autocomplete-python/lib/provider.coffee:50:10)
    at Socket.<anonymous> (/usr/share/atom-beta/resources/app.asar/src/buffered-process.js:85:13)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:520:20)
```

### Commands

```
  2x -0:08.1.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:07.4.0 core:select-down (atom-text-editor.editor.is-focused)
  2x -0:07.2.0 core:delete (atom-text-editor.editor.is-focused)
     -0:05.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:05.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:05.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:05.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:05.2.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:05.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:05.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:02.9.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:02.9.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:01.7.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:01.7.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:01.5.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:01.5.0 core:cancel (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "remember-session"
    ],
    "ignoredNames": [
      ".git .pyc"
    ]
  },
  "autocomplete-python": {
    "addBracketAfterFunction": true,
    "useSnippets": "required"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.15
autoclose-html, v0.19.0
autocomplete-python, v0.9.0
jquery-snippets, v11.0.0
language-asp, v1.0.0
language-vbscript, v0.6.1
linter, v1.9.1
linter-flake8, v1.9.1
linter-htmlhint, v0.2.1
linter-pep8, v1.0.1
pretty-json, v0.4.1
project-manager, v2.6.5
python-tools, v0.6.5
smart-tab-name, v1.0.4
whitespace, v0.32.0

# Dev
No dev packages
```

**Comment by sadovnychyi** [comment]
Is it happening all the time or only in some cases?

cc @JostCrow

**Comment by JostCrow** [comment]
For me this is happening all the time. I also reloaded atom then the error
was gone for a few minutes and autocomplete worked again. But after a few
minutes the error was shown again. It wil produce an error about every
20-30 seconds

On Wed, 28 Oct 2015 01:33 Dmitry Sadovnychyi <notifications@github.com>
wrote:

> Is it happening all the time or only in some cases?
>
> cc @JostCrow <https://github.com/JostCrow>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sadovnychyi/autocomplete-python/issues/95#issuecomment-151683573>
> .
>
-- 

Jorik Kraaikamp

**Comment by sadovnychyi** [comment]
Strange, I need more info to catch this. I think I'll release new version with optional debug flags to get more info about communication between plugin and jedi. And then will ask you to give me some output from your logs.

**Comment by JostCrow** [comment]
Ok. I will update this as soon as I can.


Kind regards,
*Jorik Kraaikamp*

Jorikkraaikamp@gmail.com

**Comment by sadovnychyi** [comment]
I just pushed 0.9.1. Please update to it, restart your editor, go into settings and select `Output debug logs`.
![image](https://cloud.githubusercontent.com/assets/193864/10783110/4627de64-7d90-11e5-978c-aa80c63d2f12.png)

After that open Developer Tools and select Console tab.
![image](https://cloud.githubusercontent.com/assets/193864/10783145/800b8d4c-7d90-11e5-8201-03daaeb94f80.png)
Now, in any python file try to trigger autocomplete. You should see logs getting populated.
After you will get this error, save logs in file and show them to me. Care about your privacy because logs contains source code of files you have edited.
![image](https://cloud.githubusercontent.com/assets/193864/10783165/ab364688-7d90-11e5-9167-24982abb18a8.png)

**Comment by JostCrow** [comment]
When the error will occur again i will show you the output. Because I restarted atom the error does not show yet.

**Comment by sadovnychyi** [comment]
Just pushed 0.9.2 with some changes. Please check it out and send me a new log if issue still persists.

**Comment by JostCrow** [comment]
Ok. Thanks

On Wed, 28 Oct 2015 12:44 Dmitry Sadovnychyi <notifications@github.com>
wrote:

> Just pushed 0.9.2 with some changes. Please check it out and send me a new
> log if issue still persists.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sadovnychyi/autocomplete-python/issues/95#issuecomment-151815734>
> .
>
-- 

Jorik Kraaikamp

**Comment by cmehay** [comment]
Just want to say that the problem seems to be appear after an upgrade to 0.9.2.

```
SyntaxError: Unexpected token {
  at Object.parse (native)
  at [object Object].module.exports._deserialize (/home/goldy/.atom/packages/autocomplete-python/lib/provider.coffee:7:3)
  at provider.BufferedProcess.stdout (/home/goldy/.atom/packages/autocomplete-python/lib/provider.coffee:50:10)
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:85:13)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at Pipe.onread (net.js:520:20)
```

**Comment by sadovnychyi** [comment]
Could you generate a log file?

**Comment by cmehay** [comment]
@sadovnychyi sorry I removed my comment, I just restarted atom to fix the problem.

**Comment by sadovnychyi** [comment]
So I guess this is fixed now.
