### ISSUE TITLE
Fuzzy completion of variables/functions à la Sublime Text

### ISSUE THREAD

**Issue by slhck** [sadovnychyi/autocomplete-python#97]
In Sublime Text, completion is fuzzy, i.e., typing `stdr` will match `stderr`.

![image](https://cloud.githubusercontent.com/assets/582444/10765071/69bea976-7cd1-11e5-9cca-4e065bbd77df.png)

With this package, completion seems to be sequential, i.e., I have to type `stde` to match `stderr`.

![image](https://cloud.githubusercontent.com/assets/582444/10765097/8d62a8e6-7cd1-11e5-948b-f8abd3d031db.png)

Having fuzzy completion would make this plugin much more efficient, since some variables may only differ at the end, or be uniquely identified through combinations of characters in it, rather than their first characters.

Would this be possible to implement? Apologies if this has already been considered or dismissed before, but I couldn't find anything related to "fuzzy" matching here.

**Comment by patrys** [comment]
Which version of `autocomplete-python` are you using? Two versions ago we have implemented exactly that.

**Comment by sadovnychyi** [comment]
![image](https://cloud.githubusercontent.com/assets/193864/10776360/a5bc2550-7d4b-11e5-8491-a34ffd27a89f.png)

**Comment by slhck** [comment]
I already was on the latest version; apparently a restart of Atom fixed it. Thanks.
