### ISSUE TITLE
Launching from activated env not necessary?

### ISSUE THREAD

**Issue by ksofa2** [sadovnychyi/autocomplete-python#99]
From the documentation: "If using a virtualenv with third-party packages, be sure to launch Atom from the activated virtualenv to get completion for your third-party packages"

Is this necessary if using the Extra PATH setting and $PROJECT variable? (e.g.: $PROJECT/env/lib/python2.7/site-packages). This to work well for me.

**Comment by patrys** [comment]
It's not necessary if you set the extra path correctly and if your venv uses CPython 2.x. If you want to use Python 3 or pypy then you need to make sure the correct interpreter is available as `python` in `$PATH`.

**Comment by ksofa2** [comment]
Is it worth updating the documentation? (I can create a pull request.)

**Comment by sadovnychyi** [comment]
Yeah you can. If you can configure extra PATH – its better, if not – just launch from activated venv.
As I remember in some cases Atom cannot recognize environment variables even when launched from command line. So setting up extra path is preferred way.
